-- 病人手术通知表（源，全 VARCHAR 镜像，D10）
-- 列清单来源：docs/lineage/原始表结构示例数据（MySQL数据库的4张表+绩效4张表）.xlsx
-- D10：全列 1:1 镜像 + 全 VARCHAR。列宽分档（utf8mb4 撞过 InnoDB 65535 字节行上限后收紧，2026-08-06 实测）：
-- 默认 64 字符（UUID/代码/时间戳字符串）；长文本关键字 500；JSON 小字段 300；JSON 大字段 1000
-- 本表 JSON 列：EXTEND_INFO

DROP TABLE IF EXISTS `pat_surgery_notice`;
CREATE TABLE `pat_surgery_notice` (
  `ID` VARCHAR(64) NOT NULL COMMENT '主键（业务侧生成，非自增）',
  `TYPE` VARCHAR(64) NULL,
  `SYNC_ID` VARCHAR(64) NULL,
  `PATIENT_ID` VARCHAR(64) NULL,
  `APPLY_DEPT_ID` VARCHAR(64) NULL,
  `APPLY_USER_ID` VARCHAR(64) NULL,
  `APPLY_TIME` VARCHAR(64) NULL,
  `APPLY_START_TIME` VARCHAR(64) NULL,
  `SURGERY_DOCTOR_ID` VARCHAR(64) NULL,
  `DOCTOR_DEPT_ID` VARCHAR(64) NULL,
  `SURGERY_DATE` VARCHAR(64) NULL,
  `BODYPOSITION_CODE` VARCHAR(64) NULL,
  `OR_DEPT_ID` VARCHAR(64) NULL,
  `EC_DEPT_ID` VARCHAR(64) NULL,
  `AN_DEPT_ID` VARCHAR(64) NULL,
  `ISOLATION_CODE` VARCHAR(64) NULL,
  `IS_SECOND` VARCHAR(64) NULL,
  `SECOND_REASON` VARCHAR(500) NULL,
  `SECOND_LINK_ID` VARCHAR(64) NULL,
  `ANES_TYPE_CODE` VARCHAR(64) NULL,
  `ANES_TYPE_NAME_APPLY` VARCHAR(64) NULL,
  `ROOM_SERIAL` VARCHAR(64) NULL,
  `SURGERY_SERIAL` VARCHAR(64) NULL,
  `SEPICAL_PREPARATION` VARCHAR(500) NULL,
  `INSTRUMENT_REQUIREMENT` VARCHAR(500) NULL,
  `REMARK` VARCHAR(500) NULL,
  `IS_REGISTER` VARCHAR(64) NULL,
  `IS_RESERVE` VARCHAR(64) NULL,
  `IS_URGENT` VARCHAR(64) NULL,
  `IS_FROZEN` VARCHAR(64) NULL,
  `EXTEND_INFO` VARCHAR(300) NULL,
  `VALID` VARCHAR(64) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病人手术通知表（源，全 VARCHAR 镜像，D10）';
