-- 医生人员表（源，全 VARCHAR 镜像，D10）
-- 列清单来源：docs/lineage/原始表结构示例数据（MySQL数据库的4张表+绩效4张表）.xlsx
-- D10：全列 1:1 镜像 + 全 VARCHAR。列宽分档（utf8mb4 撞过 InnoDB 65535 字节行上限后收紧，2026-08-06 实测）：
-- 默认 64 字符（UUID/代码/时间戳字符串）；长文本关键字 500；JSON 小字段 300；JSON 大字段 1000
-- 本表 JSON 列：EXTEND_ATTRIBUTE, SIGNATURE

DROP TABLE IF EXISTS `sys_user`;
CREATE TABLE `sys_user` (
  `ID` VARCHAR(64) NOT NULL COMMENT '主键（业务侧生成，非自增）',
  `DEPT_ID` VARCHAR(64) NULL,
  `HOSPITAL_ID` VARCHAR(64) NULL,
  `SYNC_ID` VARCHAR(64) NULL,
  `CA_SYNC_ID` VARCHAR(64) NULL,
  `NAME` VARCHAR(64) NULL,
  `ALIAS` VARCHAR(64) NULL,
  `GENDER` VARCHAR(64) NULL,
  `BIRTHDAY` VARCHAR(64) NULL,
  `TYPE` VARCHAR(64) NULL,
  `PHOTO` VARCHAR(64) NULL,
  `SIGNATURE` TEXT NULL,
  `FINGERPRINT` VARCHAR(64) NULL,
  `EMAIL` VARCHAR(64) NULL,
  `PHONE_NUMBER` VARCHAR(64) NULL,
  `WECHAT_NUMBER` VARCHAR(64) NULL,
  `JOB_NUMBER` VARCHAR(64) NULL,
  `ID_CARD` VARCHAR(64) NULL,
  `JOB_TITLE_CODE` VARCHAR(64) NULL,
  `JOB_TITLE` VARCHAR(64) NULL,
  `JOB_TITLE_YEAR` VARCHAR(64) NULL,
  `JOINING_TIME` VARCHAR(64) NULL,
  `DOCTOR_CERT_CODE` VARCHAR(64) NULL,
  `ENERGY_LEVEL` VARCHAR(64) NULL,
  `DESCRIPTION` VARCHAR(500) NULL,
  `MEDICAL_TYPE` VARCHAR(64) NULL,
  `EDUCATION_CODE` VARCHAR(64) NULL,
  `GRADUATE_INSTITUTIONS` VARCHAR(64) NULL,
  `MAJOR` VARCHAR(64) NULL,
  `EXTEND_ATTRIBUTE` VARCHAR(300) NULL,
  `VALID` VARCHAR(64) NULL,
  `TAG` VARCHAR(64) NULL,
  `MODIFIER_ID` VARCHAR(64) NULL,
  `MODIFY_TIME` VARCHAR(64) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生人员表（源，全 VARCHAR 镜像，D10）';
