language=chinese
install.path=/data/install_datasophon
frameCode=DDP-1.0.0
clusterId=17
rows=200
timeOutPeriodOne=1
timeOutPeriodTwo=2
HADOOP_HOME=/data/install_datasophon/hadoop
INIT_HOME=/data/datasophon/datasophon-init
MASTER_INSTALL_HOME=/data/datasophon
id_rsa=/root/.ssh/id_rsa
ssh_port=22

# mysql config
mysql.ip=127.0.0.1
mysql.port=3306
mysql.database=datasophon
mysql.username=root
mysql.password=localmysql

# nexus
nexus.enable=true
nexus.ip=192.168.2.200
nexus.port=8091
nexus.username=admin
nexus.password=u4Gkp19TRcKKlTCLNA1pyA==

# rustfs
rustfs.ip=192.168.2.173
rustfs.port=9040
rustfs.access_key=admin
rustfs.secret_key=u4Gkp19TRcKKlTCLNA1pyA==

# server
server.port=8081

temp.dir=/tmp/datasophon

k8s.agent.nodePort=32552
# k8s agent auth
k8s.agent.auth.enabled=false
k8s.agent.auth.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlf/Z2stM14xv/4RgtB92XXH7xniH0AqCT1qDA72kk0qMJoySF83PAKqXuZof76EMMhOAaQstOGRFNpIhzNH4Au4aD+ubF6rtTffp0yUnk0MJhwVudP6/C6n+ZRB4Wo5o7lVhUAlW09vy7ULOwkH7mkbwJQ4PKHsFwqRblhpObJ+NtJjA/a4v+m5wx25cPTuOvVr58mdE2HjrssxOwsEtcB/ri+ZMvmiqCpV3b3ya7o08XLnRu/2NYujrxK32PJJog9rEciDq8z/zYvo1GisxLSnjcVb48NyBKWv1MIeOjt0i23p4Ig1/KhW1QvySLUrPhme5aSqlBt0//E875TPYQQIDAQAB
k8s.agent.auth.private.key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCV/9nay0zXjG//hGC0H3ZdcfvGeIfQCoJPWoMDvaSTSowmjJIXzc8Aqpe5mh/voQwyE4BpCy04ZEU2kiHM0fgC7hoP65sXqu1N9+nTJSeTQwmHBW50/r8Lqf5lEHhajmjuVWFQCVbT2/LtQs7CQfuaRvAlDg8oewXCpFuWGk5sn420mMD9ri/6bnDHblw9O469WvnyZ0TYeOuyzE7CwS1wH+uL5ky+aKoKlXdvfJrujTxcudG7/Y1i6OvErfY8kmiD2sRyIOrzP/Ni+jUaKzEtKeNxVvjw3IEpa/Uwh46O3SLbengiDX8qFbVC/JItSs+GZ7lpKqUG3T/8TzvlM9hBAgMBAAECggEAWkA+zC5WZbrSCGOV68qiZUcXvir3TG2GSkijW7TXOOg5u1gI7tmeG0CJWdsqK/wyYk7pjEp1QuDR5Cu4uov7NYgdlkakYnEtpyPrRGeukCRdryfNdgdw24vEzPpD7/iPmhc1HfsAiyhj2e3AiZE52XGlPCZhaHHc3WgW0xGw7hmFkmgSUtShgvrJF2e8pdokgFH6lG2J4IVtgXW7vkaVlbrQEyeYbiSiEsXKNkGRT5LWoL9dXJaUgUvZVsRm2s+2e90jPmWz0Z66HaT5lnJN8LVD5kc8rmSSTjqZt74iux/VXNE0YEqan8SIJ3yA4DsB3VcuoufxOWtjgHkCn9E+IQKBgQDUNHnm4eqSe6+8CxWwfKvd8/MYPpZlHzqcm+8JHnSSDRllZgGxvqeyWXyxnEQ0vRfZ+fuhPIXz2mWizx6xrVoDXHtkeNQ6vahSjdOA7DV0v2wecRYclGOoRvaJneZxBIEQPlXcSnn9TLNNBqWb7Zu5YDqgqoFiFipOFTF0FWTqVwKBgQC09NbjSFVS3QkbJGx8FtZcvGEcZvKXpZ2TPRG/QOAwNjNpiyxcHg1rDIH3Pkp57AsHKQBev6LolTw3paR5R/iozh7ShmhbS8DKWrA9RbjWONkcVj3URjwTZmZpHdKl0PpgBcEkAzXYU0m8w44DaQBAUfPjPE6n2JHuwvBDXZ/jJwKBgEQ/ADltzLgBiVoLopUY81k1fKf+cPXinkIBsFWZctoJ1nIS5VaZv2sPdpfUbucbLVGQIQoQ4e+z/F3pCLER1FIiaxi7911Q45JxRGVBEkwSyB3eNsNIQei7scw+eP89+JgVxB1N4n/BLCUIjzhfqWZr+U70pxm5kS99h2MTAlqPAoGAFw4y6tZmeJ5M8LZdVBocycf+n33GXuftAbuALVv4tGvTdRkUV9BEaWU4keXP22Tlqs3gjDHicbvB5l0mbYVr+yX3617QoQEv2Rhg6A2gFTs8/k1Gp2sjcF1VowL3ucS8gct55jq6e4txE6neyDRyob9PUZ53bw862K7hqdOd8XUCgYEAzoPcblgpjTYUtD2FMZkSqZcCK+hVbN/6C/SPaHfgjk0fmbuKIRsq9GeeND01UAvKmb/HTVPFcz+ptw363dX0J7uiFbUTUuFbVbROP4ixYM9YPrOArNiLHpP+KiHj+kKgT6RKiRJOpm13DpCSlYcOYMYLe6NYNCYkZW18rD+hXq4=
k8s.agent.auth.replay.window.seconds=300
