language=chinese
install.path=/data/install_datasophon
frameCode=DDP-1.0.0
clusterId=17
rows=200
times=20
timeOutPeriodOne=1
timeOutPeriodTwo=2
HADOOP_HOME=/data/install_datasophon/hadoop
INIT_HOME=/data/datasophon/datasophon-init
MASTER_INSTALL_HOME=/data/datasophon
id_rsa=/root/.ssh/id_rsa
ssh_port=22

# mysql config
mysql.ip=192.168.2.202
mysql.port=3306
mysql.database=datasophon
mysql.username=datasophon
mysql.password=fI5sQ4yQ4fP5

# nexus
nexus.enable=true
nexus.ip=192.168.2.200
nexus.port=8091
nexus.username=admin
nexus.password=u4Gkp19TRcKKlTCLNA1pyA==

# rustfs
rustfs.ip=192.168.2.173
rustfs.port=9040
rustfs.access_key=admin
rustfs.secret_key=u4Gkp19TRcKKlTCLNA1pyA==

# server
masterHost=app1
server.port=8081
server.address=0.0.0.0

temp.dir=/tmp/datasophon

vos.k8sAgent.nodePort=32552
