// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

/**
 * <pre>
 **
 * 告警配置生成请求。
 *
 * config_map_json = GenerateAlertConfigCommand.configFileMap 序列化为
 *                   List&amp;lt;AlertConfigEntry&amp;gt; 的 JSON（解决 Generators 作为 Map key 的问题）。
 * </pre>
 *
 * Protobuf type {@code com.datasophon.grpc.AlertConfigRequest}
 */
public final class AlertConfigRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.datasophon.grpc.AlertConfigRequest)
    AlertConfigRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AlertConfigRequest.newBuilder() to construct.
  private AlertConfigRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AlertConfigRequest() {
    configMapJson_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AlertConfigRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_AlertConfigRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_AlertConfigRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.datasophon.grpc.api.AlertConfigRequest.class, com.datasophon.grpc.api.AlertConfigRequest.Builder.class);
  }

  public static final int CLUSTER_ID_FIELD_NUMBER = 1;
  private int clusterId_ = 0;
  /**
   * <code>int32 cluster_id = 1;</code>
   * @return The clusterId.
   */
  @java.lang.Override
  public int getClusterId() {
    return clusterId_;
  }

  public static final int CONFIG_MAP_JSON_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object configMapJson_ = "";
  /**
   * <code>string config_map_json = 2;</code>
   * @return The configMapJson.
   */
  @java.lang.Override
  public java.lang.String getConfigMapJson() {
    java.lang.Object ref = configMapJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      configMapJson_ = s;
      return s;
    }
  }
  /**
   * <code>string config_map_json = 2;</code>
   * @return The bytes for configMapJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConfigMapJsonBytes() {
    java.lang.Object ref = configMapJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      configMapJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (clusterId_ != 0) {
      output.writeInt32(1, clusterId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(configMapJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, configMapJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (clusterId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, clusterId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(configMapJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, configMapJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.datasophon.grpc.api.AlertConfigRequest)) {
      return super.equals(obj);
    }
    com.datasophon.grpc.api.AlertConfigRequest other = (com.datasophon.grpc.api.AlertConfigRequest) obj;

    if (getClusterId()
        != other.getClusterId()) return false;
    if (!getConfigMapJson()
        .equals(other.getConfigMapJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLUSTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClusterId();
    hash = (37 * hash) + CONFIG_MAP_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getConfigMapJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.datasophon.grpc.api.AlertConfigRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.AlertConfigRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.AlertConfigRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.AlertConfigRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.AlertConfigRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.AlertConfigRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.AlertConfigRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.datasophon.grpc.api.AlertConfigRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.datasophon.grpc.api.AlertConfigRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.datasophon.grpc.api.AlertConfigRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.datasophon.grpc.api.AlertConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.datasophon.grpc.api.AlertConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.datasophon.grpc.api.AlertConfigRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 告警配置生成请求。
   *
   * config_map_json = GenerateAlertConfigCommand.configFileMap 序列化为
   *                   List&amp;lt;AlertConfigEntry&amp;gt; 的 JSON（解决 Generators 作为 Map key 的问题）。
   * </pre>
   *
   * Protobuf type {@code com.datasophon.grpc.AlertConfigRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.datasophon.grpc.AlertConfigRequest)
      com.datasophon.grpc.api.AlertConfigRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_AlertConfigRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_AlertConfigRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.datasophon.grpc.api.AlertConfigRequest.class, com.datasophon.grpc.api.AlertConfigRequest.Builder.class);
    }

    // Construct using com.datasophon.grpc.api.AlertConfigRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      clusterId_ = 0;
      configMapJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_AlertConfigRequest_descriptor;
    }

    @java.lang.Override
    public com.datasophon.grpc.api.AlertConfigRequest getDefaultInstanceForType() {
      return com.datasophon.grpc.api.AlertConfigRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.datasophon.grpc.api.AlertConfigRequest build() {
      com.datasophon.grpc.api.AlertConfigRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.datasophon.grpc.api.AlertConfigRequest buildPartial() {
      com.datasophon.grpc.api.AlertConfigRequest result = new com.datasophon.grpc.api.AlertConfigRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.datasophon.grpc.api.AlertConfigRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.clusterId_ = clusterId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.configMapJson_ = configMapJson_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.datasophon.grpc.api.AlertConfigRequest) {
        return mergeFrom((com.datasophon.grpc.api.AlertConfigRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.datasophon.grpc.api.AlertConfigRequest other) {
      if (other == com.datasophon.grpc.api.AlertConfigRequest.getDefaultInstance()) return this;
      if (other.getClusterId() != 0) {
        setClusterId(other.getClusterId());
      }
      if (!other.getConfigMapJson().isEmpty()) {
        configMapJson_ = other.configMapJson_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              clusterId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              configMapJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int clusterId_ ;
    /**
     * <code>int32 cluster_id = 1;</code>
     * @return The clusterId.
     */
    @java.lang.Override
    public int getClusterId() {
      return clusterId_;
    }
    /**
     * <code>int32 cluster_id = 1;</code>
     * @param value The clusterId to set.
     * @return This builder for chaining.
     */
    public Builder setClusterId(int value) {

      clusterId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cluster_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      clusterId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object configMapJson_ = "";
    /**
     * <code>string config_map_json = 2;</code>
     * @return The configMapJson.
     */
    public java.lang.String getConfigMapJson() {
      java.lang.Object ref = configMapJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        configMapJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string config_map_json = 2;</code>
     * @return The bytes for configMapJson.
     */
    public com.google.protobuf.ByteString
        getConfigMapJsonBytes() {
      java.lang.Object ref = configMapJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        configMapJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string config_map_json = 2;</code>
     * @param value The configMapJson to set.
     * @return This builder for chaining.
     */
    public Builder setConfigMapJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      configMapJson_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string config_map_json = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfigMapJson() {
      configMapJson_ = getDefaultInstance().getConfigMapJson();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string config_map_json = 2;</code>
     * @param value The bytes for configMapJson to set.
     * @return This builder for chaining.
     */
    public Builder setConfigMapJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      configMapJson_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.datasophon.grpc.AlertConfigRequest)
  }

  // @@protoc_insertion_point(class_scope:com.datasophon.grpc.AlertConfigRequest)
  private static final com.datasophon.grpc.api.AlertConfigRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.datasophon.grpc.api.AlertConfigRequest();
  }

  public static com.datasophon.grpc.api.AlertConfigRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AlertConfigRequest>
      PARSER = new com.google.protobuf.AbstractParser<AlertConfigRequest>() {
    @java.lang.Override
    public AlertConfigRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AlertConfigRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AlertConfigRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.datasophon.grpc.api.AlertConfigRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

