// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_ExecResultPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_ExecResultPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\023com.datasophon.grpc\"K\n\014E" +
      "xecResultPb\022\023\n\013exec_result\030\001 \001(\010\022\020\n\010exec" +
      "_out\030\002 \001(\t\022\024\n\014exec_err_out\030\003 \001(\tB(\n\027com." +
      "datasophon.grpc.apiB\013CommonProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_datasophon_grpc_ExecResultPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_datasophon_grpc_ExecResultPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_ExecResultPb_descriptor,
        new java.lang.String[] { "ExecResult", "ExecOut", "ExecErrOut", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
