// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

/**
 * <pre>
 * 命令执行结果，对应 com.datasophon.common.utils.ExecResult
 * </pre>
 *
 * Protobuf type {@code com.datasophon.grpc.ExecResultPb}
 */
public final class ExecResultPb
        extends
            com.google.protobuf.GeneratedMessageV3
        implements
            // @@protoc_insertion_point(message_implements:com.datasophon.grpc.ExecResultPb)
            ExecResultPbOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use ExecResultPb.newBuilder() to construct.
    private ExecResultPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }
    private ExecResultPb() {
        execOut_ = "";
        execErrOut_ = "";
    }
    
    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
                                           UnusedPrivateParameter unused) {
        return new ExecResultPb();
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.datasophon.grpc.api.CommonProto.internal_static_com_datasophon_grpc_ExecResultPb_descriptor;
    }
    
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.datasophon.grpc.api.CommonProto.internal_static_com_datasophon_grpc_ExecResultPb_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.datasophon.grpc.api.ExecResultPb.class, com.datasophon.grpc.api.ExecResultPb.Builder.class);
    }
    
    public static final int EXEC_RESULT_FIELD_NUMBER = 1;
    private boolean execResult_ = false;
    /**
     * <pre>
     * true=成功
     * </pre>
     *
     * <code>bool exec_result = 1;</code>
     * @return The execResult.
     */
    @java.lang.Override
    public boolean getExecResult() {
        return execResult_;
    }
    
    public static final int EXEC_OUT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object execOut_ = "";
    /**
     * <pre>
     * 标准输出
     * </pre>
     *
     * <code>string exec_out = 2;</code>
     * @return The execOut.
     */
    @java.lang.Override
    public java.lang.String getExecOut() {
        java.lang.Object ref = execOut_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            execOut_ = s;
            return s;
        }
    }
    /**
     * <pre>
     * 标准输出
     * </pre>
     *
     * <code>string exec_out = 2;</code>
     * @return The bytes for execOut.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getExecOutBytes() {
        java.lang.Object ref = execOut_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            execOut_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int EXEC_ERR_OUT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object execErrOut_ = "";
    /**
     * <pre>
     * 错误输出
     * </pre>
     *
     * <code>string exec_err_out = 3;</code>
     * @return The execErrOut.
     */
    @java.lang.Override
    public java.lang.String getExecErrOut() {
        java.lang.Object ref = execErrOut_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            execErrOut_ = s;
            return s;
        }
    }
    /**
     * <pre>
     * 错误输出
     * </pre>
     *
     * <code>string exec_err_out = 3;</code>
     * @return The bytes for execErrOut.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getExecErrOutBytes() {
        java.lang.Object ref = execErrOut_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            execErrOut_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        
        memoizedIsInitialized = 1;
        return true;
    }
    
    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (execResult_ != false) {
            output.writeBool(1, execResult_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(execOut_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, execOut_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(execErrOut_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, execErrOut_);
        }
        getUnknownFields().writeTo(output);
    }
    
    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        
        size = 0;
        if (execResult_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(1, execResult_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(execOut_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, execOut_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(execErrOut_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, execErrOut_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.datasophon.grpc.api.ExecResultPb)) {
            return super.equals(obj);
        }
        com.datasophon.grpc.api.ExecResultPb other = (com.datasophon.grpc.api.ExecResultPb) obj;
        
        if (getExecResult() != other.getExecResult())
            return false;
        if (!getExecOut()
                .equals(other.getExecOut()))
            return false;
        if (!getExecErrOut()
                .equals(other.getExecErrOut()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }
    
    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + EXEC_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getExecResult());
        hash = (37 * hash) + EXEC_OUT_FIELD_NUMBER;
        hash = (53 * hash) + getExecOut().hashCode();
        hash = (37 * hash) + EXEC_ERR_OUT_FIELD_NUMBER;
        hash = (53 * hash) + getExecErrOut().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }
    
    public static com.datasophon.grpc.api.ExecResultPb parseFrom(
                                                                 java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.datasophon.grpc.api.ExecResultPb parseFrom(
                                                                 java.nio.ByteBuffer data,
                                                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datasophon.grpc.api.ExecResultPb parseFrom(
                                                                 com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.datasophon.grpc.api.ExecResultPb parseFrom(
                                                                 com.google.protobuf.ByteString data,
                                                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datasophon.grpc.api.ExecResultPb parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.datasophon.grpc.api.ExecResultPb parseFrom(
                                                                 byte[] data,
                                                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datasophon.grpc.api.ExecResultPb parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    public static com.datasophon.grpc.api.ExecResultPb parseFrom(
                                                                 java.io.InputStream input,
                                                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static com.datasophon.grpc.api.ExecResultPb parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }
    
    public static com.datasophon.grpc.api.ExecResultPb parseDelimitedFrom(
                                                                          java.io.InputStream input,
                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.datasophon.grpc.api.ExecResultPb parseFrom(
                                                                 com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    public static com.datasophon.grpc.api.ExecResultPb parseFrom(
                                                                 com.google.protobuf.CodedInputStream input,
                                                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.datasophon.grpc.api.ExecResultPb prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder()
                : new Builder().mergeFrom(this);
    }
    
    @java.lang.Override
    protected Builder newBuilderForType(
                                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * <pre>
     * 命令执行结果，对应 com.datasophon.common.utils.ExecResult
     * </pre>
     *
     * Protobuf type {@code com.datasophon.grpc.ExecResultPb}
     */
    public static final class Builder
            extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder>
            implements
                // @@protoc_insertion_point(builder_implements:com.datasophon.grpc.ExecResultPb)
                com.datasophon.grpc.api.ExecResultPbOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.datasophon.grpc.api.CommonProto.internal_static_com_datasophon_grpc_ExecResultPb_descriptor;
        }
        
        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.datasophon.grpc.api.CommonProto.internal_static_com_datasophon_grpc_ExecResultPb_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.datasophon.grpc.api.ExecResultPb.class, com.datasophon.grpc.api.ExecResultPb.Builder.class);
        }
        
        // Construct using com.datasophon.grpc.api.ExecResultPb.newBuilder()
        private Builder() {
            
        }
        
        private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            
        }
        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            execResult_ = false;
            execOut_ = "";
            execErrOut_ = "";
            return this;
        }
        
        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.datasophon.grpc.api.CommonProto.internal_static_com_datasophon_grpc_ExecResultPb_descriptor;
        }
        
        @java.lang.Override
        public com.datasophon.grpc.api.ExecResultPb getDefaultInstanceForType() {
            return com.datasophon.grpc.api.ExecResultPb.getDefaultInstance();
        }
        
        @java.lang.Override
        public com.datasophon.grpc.api.ExecResultPb build() {
            com.datasophon.grpc.api.ExecResultPb result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }
        
        @java.lang.Override
        public com.datasophon.grpc.api.ExecResultPb buildPartial() {
            com.datasophon.grpc.api.ExecResultPb result = new com.datasophon.grpc.api.ExecResultPb(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }
        
        private void buildPartial0(com.datasophon.grpc.api.ExecResultPb result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.execResult_ = execResult_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.execOut_ = execOut_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.execErrOut_ = execErrOut_;
            }
        }
        
        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }
        @java.lang.Override
        public Builder setField(
                                com.google.protobuf.Descriptors.FieldDescriptor field,
                                java.lang.Object value) {
            return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
                                  com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
                                  com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
                                        com.google.protobuf.Descriptors.FieldDescriptor field,
                                        int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
                                        com.google.protobuf.Descriptors.FieldDescriptor field,
                                        java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.datasophon.grpc.api.ExecResultPb) {
                return mergeFrom((com.datasophon.grpc.api.ExecResultPb) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }
        
        public Builder mergeFrom(com.datasophon.grpc.api.ExecResultPb other) {
            if (other == com.datasophon.grpc.api.ExecResultPb.getDefaultInstance())
                return this;
            if (other.getExecResult() != false) {
                setExecResult(other.getExecResult());
            }
            if (!other.getExecOut().isEmpty()) {
                execOut_ = other.execOut_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (!other.getExecErrOut().isEmpty()) {
                execErrOut_ = other.execErrOut_;
                bitField0_ |= 0x00000004;
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }
        
        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }
        
        @java.lang.Override
        public Builder mergeFrom(
                                 com.google.protobuf.CodedInputStream input,
                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            execResult_ = input.readBool();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 8
                        case 18: {
                            execOut_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 26: {
                            execErrOut_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 26
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }
        private int bitField0_;
        
        private boolean execResult_;
        /**
         * <pre>
         * true=成功
         * </pre>
         *
         * <code>bool exec_result = 1;</code>
         * @return The execResult.
         */
        @java.lang.Override
        public boolean getExecResult() {
            return execResult_;
        }
        /**
         * <pre>
         * true=成功
         * </pre>
         *
         * <code>bool exec_result = 1;</code>
         * @param value The execResult to set.
         * @return This builder for chaining.
         */
        public Builder setExecResult(boolean value) {
            
            execResult_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        /**
         * <pre>
         * true=成功
         * </pre>
         *
         * <code>bool exec_result = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearExecResult() {
            bitField0_ = (bitField0_ & ~0x00000001);
            execResult_ = false;
            onChanged();
            return this;
        }
        
        private java.lang.Object execOut_ = "";
        /**
         * <pre>
         * 标准输出
         * </pre>
         *
         * <code>string exec_out = 2;</code>
         * @return The execOut.
         */
        public java.lang.String getExecOut() {
            java.lang.Object ref = execOut_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                execOut_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <pre>
         * 标准输出
         * </pre>
         *
         * <code>string exec_out = 2;</code>
         * @return The bytes for execOut.
         */
        public com.google.protobuf.ByteString getExecOutBytes() {
            java.lang.Object ref = execOut_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                execOut_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <pre>
         * 标准输出
         * </pre>
         *
         * <code>string exec_out = 2;</code>
         * @param value The execOut to set.
         * @return This builder for chaining.
         */
        public Builder setExecOut(
                                  java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            execOut_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <pre>
         * 标准输出
         * </pre>
         *
         * <code>string exec_out = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearExecOut() {
            execOut_ = getDefaultInstance().getExecOut();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }
        /**
         * <pre>
         * 标准输出
         * </pre>
         *
         * <code>string exec_out = 2;</code>
         * @param value The bytes for execOut to set.
         * @return This builder for chaining.
         */
        public Builder setExecOutBytes(
                                       com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            execOut_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        
        private java.lang.Object execErrOut_ = "";
        /**
         * <pre>
         * 错误输出
         * </pre>
         *
         * <code>string exec_err_out = 3;</code>
         * @return The execErrOut.
         */
        public java.lang.String getExecErrOut() {
            java.lang.Object ref = execErrOut_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                execErrOut_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <pre>
         * 错误输出
         * </pre>
         *
         * <code>string exec_err_out = 3;</code>
         * @return The bytes for execErrOut.
         */
        public com.google.protobuf.ByteString getExecErrOutBytes() {
            java.lang.Object ref = execErrOut_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                execErrOut_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <pre>
         * 错误输出
         * </pre>
         *
         * <code>string exec_err_out = 3;</code>
         * @param value The execErrOut to set.
         * @return This builder for chaining.
         */
        public Builder setExecErrOut(
                                     java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            execErrOut_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }
        /**
         * <pre>
         * 错误输出
         * </pre>
         *
         * <code>string exec_err_out = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearExecErrOut() {
            execErrOut_ = getDefaultInstance().getExecErrOut();
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }
        /**
         * <pre>
         * 错误输出
         * </pre>
         *
         * <code>string exec_err_out = 3;</code>
         * @param value The bytes for execErrOut to set.
         * @return This builder for chaining.
         */
        public Builder setExecErrOutBytes(
                                          com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            execErrOut_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
                                              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }
        
        @java.lang.Override
        public final Builder mergeUnknownFields(
                                                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        
        // @@protoc_insertion_point(builder_scope:com.datasophon.grpc.ExecResultPb)
    }
    
    // @@protoc_insertion_point(class_scope:com.datasophon.grpc.ExecResultPb)
    private static final com.datasophon.grpc.api.ExecResultPb DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new com.datasophon.grpc.api.ExecResultPb();
    }
    
    public static com.datasophon.grpc.api.ExecResultPb getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }
    
    private static final com.google.protobuf.Parser<ExecResultPb> PARSER = new com.google.protobuf.AbstractParser<ExecResultPb>() {
        @java.lang.Override
        public ExecResultPb parsePartialFrom(
                                             com.google.protobuf.CodedInputStream input,
                                             com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };
    
    public static com.google.protobuf.Parser<ExecResultPb> parser() {
        return PARSER;
    }
    
    @java.lang.Override
    public com.google.protobuf.Parser<ExecResultPb> getParserForType() {
        return PARSER;
    }
    
    @java.lang.Override
    public com.datasophon.grpc.api.ExecResultPb getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
    
}
