// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

/**
 * <pre>
 **
 * 覆盖三类 Actor：
 *   - ExecuteCmdActor  →  commands（命令 + 参数列表）
 *   - RMStateActor     →  command_line（单行 shell 命令）
 *   - NMStateActor     →  command_line（单行 shell 命令）
 * 两个字段互斥，服务端优先判断 command_line 是否非空。
 * </pre>
 *
 * Protobuf type {@code com.datasophon.grpc.ExecuteCmdRequest}
 */
public final class ExecuteCmdRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.datasophon.grpc.ExecuteCmdRequest)
    ExecuteCmdRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteCmdRequest.newBuilder() to construct.
  private ExecuteCmdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteCmdRequest() {
    commands_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    commandLine_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecuteCmdRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_ExecuteCmdRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.datasophon.grpc.api.ExecuteCmdRequest.class, com.datasophon.grpc.api.ExecuteCmdRequest.Builder.class);
  }

  public static final int COMMANDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList commands_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string commands = 1;</code>
   * @return A list containing the commands.
   */
  public com.google.protobuf.ProtocolStringList
      getCommandsList() {
    return commands_;
  }
  /**
   * <code>repeated string commands = 1;</code>
   * @return The count of commands.
   */
  public int getCommandsCount() {
    return commands_.size();
  }
  /**
   * <code>repeated string commands = 1;</code>
   * @param index The index of the element to return.
   * @return The commands at the given index.
   */
  public java.lang.String getCommands(int index) {
    return commands_.get(index);
  }
  /**
   * <code>repeated string commands = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the commands at the given index.
   */
  public com.google.protobuf.ByteString
      getCommandsBytes(int index) {
    return commands_.getByteString(index);
  }

  public static final int COMMAND_LINE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object commandLine_ = "";
  /**
   * <code>string command_line = 2;</code>
   * @return The commandLine.
   */
  @java.lang.Override
  public java.lang.String getCommandLine() {
    java.lang.Object ref = commandLine_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commandLine_ = s;
      return s;
    }
  }
  /**
   * <code>string command_line = 2;</code>
   * @return The bytes for commandLine.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommandLineBytes() {
    java.lang.Object ref = commandLine_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commandLine_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < commands_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commands_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commandLine_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, commandLine_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < commands_.size(); i++) {
        dataSize += computeStringSizeNoTag(commands_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCommandsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commandLine_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, commandLine_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.datasophon.grpc.api.ExecuteCmdRequest)) {
      return super.equals(obj);
    }
    com.datasophon.grpc.api.ExecuteCmdRequest other = (com.datasophon.grpc.api.ExecuteCmdRequest) obj;

    if (!getCommandsList()
        .equals(other.getCommandsList())) return false;
    if (!getCommandLine()
        .equals(other.getCommandLine())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCommandsCount() > 0) {
      hash = (37 * hash) + COMMANDS_FIELD_NUMBER;
      hash = (53 * hash) + getCommandsList().hashCode();
    }
    hash = (37 * hash) + COMMAND_LINE_FIELD_NUMBER;
    hash = (53 * hash) + getCommandLine().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.datasophon.grpc.api.ExecuteCmdRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.ExecuteCmdRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.ExecuteCmdRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.ExecuteCmdRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.ExecuteCmdRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.ExecuteCmdRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.ExecuteCmdRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.datasophon.grpc.api.ExecuteCmdRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.datasophon.grpc.api.ExecuteCmdRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.datasophon.grpc.api.ExecuteCmdRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.datasophon.grpc.api.ExecuteCmdRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.datasophon.grpc.api.ExecuteCmdRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.datasophon.grpc.api.ExecuteCmdRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 覆盖三类 Actor：
   *   - ExecuteCmdActor  →  commands（命令 + 参数列表）
   *   - RMStateActor     →  command_line（单行 shell 命令）
   *   - NMStateActor     →  command_line（单行 shell 命令）
   * 两个字段互斥，服务端优先判断 command_line 是否非空。
   * </pre>
   *
   * Protobuf type {@code com.datasophon.grpc.ExecuteCmdRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.datasophon.grpc.ExecuteCmdRequest)
      com.datasophon.grpc.api.ExecuteCmdRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_ExecuteCmdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.datasophon.grpc.api.ExecuteCmdRequest.class, com.datasophon.grpc.api.ExecuteCmdRequest.Builder.class);
    }

    // Construct using com.datasophon.grpc.api.ExecuteCmdRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      commands_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      commandLine_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor;
    }

    @java.lang.Override
    public com.datasophon.grpc.api.ExecuteCmdRequest getDefaultInstanceForType() {
      return com.datasophon.grpc.api.ExecuteCmdRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.datasophon.grpc.api.ExecuteCmdRequest build() {
      com.datasophon.grpc.api.ExecuteCmdRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.datasophon.grpc.api.ExecuteCmdRequest buildPartial() {
      com.datasophon.grpc.api.ExecuteCmdRequest result = new com.datasophon.grpc.api.ExecuteCmdRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.datasophon.grpc.api.ExecuteCmdRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        commands_.makeImmutable();
        result.commands_ = commands_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.commandLine_ = commandLine_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.datasophon.grpc.api.ExecuteCmdRequest) {
        return mergeFrom((com.datasophon.grpc.api.ExecuteCmdRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.datasophon.grpc.api.ExecuteCmdRequest other) {
      if (other == com.datasophon.grpc.api.ExecuteCmdRequest.getDefaultInstance()) return this;
      if (!other.commands_.isEmpty()) {
        if (commands_.isEmpty()) {
          commands_ = other.commands_;
          bitField0_ |= 0x00000001;
        } else {
          ensureCommandsIsMutable();
          commands_.addAll(other.commands_);
        }
        onChanged();
      }
      if (!other.getCommandLine().isEmpty()) {
        commandLine_ = other.commandLine_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureCommandsIsMutable();
              commands_.add(s);
              break;
            } // case 10
            case 18: {
              commandLine_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList commands_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureCommandsIsMutable() {
      if (!commands_.isModifiable()) {
        commands_ = new com.google.protobuf.LazyStringArrayList(commands_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string commands = 1;</code>
     * @return A list containing the commands.
     */
    public com.google.protobuf.ProtocolStringList
        getCommandsList() {
      commands_.makeImmutable();
      return commands_;
    }
    /**
     * <code>repeated string commands = 1;</code>
     * @return The count of commands.
     */
    public int getCommandsCount() {
      return commands_.size();
    }
    /**
     * <code>repeated string commands = 1;</code>
     * @param index The index of the element to return.
     * @return The commands at the given index.
     */
    public java.lang.String getCommands(int index) {
      return commands_.get(index);
    }
    /**
     * <code>repeated string commands = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the commands at the given index.
     */
    public com.google.protobuf.ByteString
        getCommandsBytes(int index) {
      return commands_.getByteString(index);
    }
    /**
     * <code>repeated string commands = 1;</code>
     * @param index The index to set the value at.
     * @param value The commands to set.
     * @return This builder for chaining.
     */
    public Builder setCommands(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCommandsIsMutable();
      commands_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string commands = 1;</code>
     * @param value The commands to add.
     * @return This builder for chaining.
     */
    public Builder addCommands(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCommandsIsMutable();
      commands_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string commands = 1;</code>
     * @param values The commands to add.
     * @return This builder for chaining.
     */
    public Builder addAllCommands(
        java.lang.Iterable<java.lang.String> values) {
      ensureCommandsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, commands_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string commands = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommands() {
      commands_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string commands = 1;</code>
     * @param value The bytes of the commands to add.
     * @return This builder for chaining.
     */
    public Builder addCommandsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureCommandsIsMutable();
      commands_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object commandLine_ = "";
    /**
     * <code>string command_line = 2;</code>
     * @return The commandLine.
     */
    public java.lang.String getCommandLine() {
      java.lang.Object ref = commandLine_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandLine_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string command_line = 2;</code>
     * @return The bytes for commandLine.
     */
    public com.google.protobuf.ByteString
        getCommandLineBytes() {
      java.lang.Object ref = commandLine_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandLine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string command_line = 2;</code>
     * @param value The commandLine to set.
     * @return This builder for chaining.
     */
    public Builder setCommandLine(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      commandLine_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string command_line = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandLine() {
      commandLine_ = getDefaultInstance().getCommandLine();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string command_line = 2;</code>
     * @param value The bytes for commandLine to set.
     * @return This builder for chaining.
     */
    public Builder setCommandLineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commandLine_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.datasophon.grpc.ExecuteCmdRequest)
  }

  // @@protoc_insertion_point(class_scope:com.datasophon.grpc.ExecuteCmdRequest)
  private static final com.datasophon.grpc.api.ExecuteCmdRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.datasophon.grpc.api.ExecuteCmdRequest();
  }

  public static com.datasophon.grpc.api.ExecuteCmdRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteCmdRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteCmdRequest>() {
    @java.lang.Override
    public ExecuteCmdRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteCmdRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteCmdRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.datasophon.grpc.api.ExecuteCmdRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

