// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

public interface FileOperateRequestOrBuilder
        extends
            // @@protoc_insertion_point(interface_extends:com.datasophon.grpc.FileOperateRequest)
            com.google.protobuf.MessageOrBuilder {
    
    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    java.lang.String getPath();
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    com.google.protobuf.ByteString getPathBytes();
    
    /**
     * <code>string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString getContentBytes();
    
    /**
     * <code>repeated string lines = 3;</code>
     * @return A list containing the lines.
     */
    java.util.List<java.lang.String> getLinesList();
    /**
     * <code>repeated string lines = 3;</code>
     * @return The count of lines.
     */
    int getLinesCount();
    /**
     * <code>repeated string lines = 3;</code>
     * @param index The index of the element to return.
     * @return The lines at the given index.
     */
    java.lang.String getLines(int index);
    /**
     * <code>repeated string lines = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the lines at the given index.
     */
    com.google.protobuf.ByteString getLinesBytes(int index);
}
