// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

/**
 * Protobuf type {@code com.datasophon.grpc.GetLogRequest}
 */
public final class GetLogRequest
        extends
            com.google.protobuf.GeneratedMessageV3
        implements
            // @@protoc_insertion_point(message_implements:com.datasophon.grpc.GetLogRequest)
            GetLogRequestOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use GetLogRequest.newBuilder() to construct.
    private GetLogRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }
    private GetLogRequest() {
        logFile_ = "";
        baseDir_ = "";
        runAsUser_ = "";
    }
    
    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
                                           UnusedPrivateParameter unused) {
        return new GetLogRequest();
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_GetLogRequest_descriptor;
    }
    
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_GetLogRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.datasophon.grpc.api.GetLogRequest.class, com.datasophon.grpc.api.GetLogRequest.Builder.class);
    }
    
    public static final int LOG_FILE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object logFile_ = "";
    /**
     * <code>string log_file = 1;</code>
     * @return The logFile.
     */
    @java.lang.Override
    public java.lang.String getLogFile() {
        java.lang.Object ref = logFile_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            logFile_ = s;
            return s;
        }
    }
    /**
     * <code>string log_file = 1;</code>
     * @return The bytes for logFile.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLogFileBytes() {
        java.lang.Object ref = logFile_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            logFile_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int BASE_DIR_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object baseDir_ = "";
    /**
     * <code>string base_dir = 2;</code>
     * @return The baseDir.
     */
    @java.lang.Override
    public java.lang.String getBaseDir() {
        java.lang.Object ref = baseDir_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            baseDir_ = s;
            return s;
        }
    }
    /**
     * <code>string base_dir = 2;</code>
     * @return The bytes for baseDir.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBaseDirBytes() {
        java.lang.Object ref = baseDir_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            baseDir_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int RUN_AS_USER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object runAsUser_ = "";
    /**
     * <code>string run_as_user = 3;</code>
     * @return The runAsUser.
     */
    @java.lang.Override
    public java.lang.String getRunAsUser() {
        java.lang.Object ref = runAsUser_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            runAsUser_ = s;
            return s;
        }
    }
    /**
     * <code>string run_as_user = 3;</code>
     * @return The bytes for runAsUser.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRunAsUserBytes() {
        java.lang.Object ref = runAsUser_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            runAsUser_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        
        memoizedIsInitialized = 1;
        return true;
    }
    
    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logFile_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, logFile_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseDir_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, baseDir_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(runAsUser_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, runAsUser_);
        }
        getUnknownFields().writeTo(output);
    }
    
    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        
        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logFile_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, logFile_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(baseDir_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, baseDir_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(runAsUser_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, runAsUser_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.datasophon.grpc.api.GetLogRequest)) {
            return super.equals(obj);
        }
        com.datasophon.grpc.api.GetLogRequest other = (com.datasophon.grpc.api.GetLogRequest) obj;
        
        if (!getLogFile()
                .equals(other.getLogFile()))
            return false;
        if (!getBaseDir()
                .equals(other.getBaseDir()))
            return false;
        if (!getRunAsUser()
                .equals(other.getRunAsUser()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }
    
    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + LOG_FILE_FIELD_NUMBER;
        hash = (53 * hash) + getLogFile().hashCode();
        hash = (37 * hash) + BASE_DIR_FIELD_NUMBER;
        hash = (53 * hash) + getBaseDir().hashCode();
        hash = (37 * hash) + RUN_AS_USER_FIELD_NUMBER;
        hash = (53 * hash) + getRunAsUser().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }
    
    public static com.datasophon.grpc.api.GetLogRequest parseFrom(
                                                                  java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.datasophon.grpc.api.GetLogRequest parseFrom(
                                                                  java.nio.ByteBuffer data,
                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datasophon.grpc.api.GetLogRequest parseFrom(
                                                                  com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.datasophon.grpc.api.GetLogRequest parseFrom(
                                                                  com.google.protobuf.ByteString data,
                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datasophon.grpc.api.GetLogRequest parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.datasophon.grpc.api.GetLogRequest parseFrom(
                                                                  byte[] data,
                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datasophon.grpc.api.GetLogRequest parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    public static com.datasophon.grpc.api.GetLogRequest parseFrom(
                                                                  java.io.InputStream input,
                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static com.datasophon.grpc.api.GetLogRequest parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }
    
    public static com.datasophon.grpc.api.GetLogRequest parseDelimitedFrom(
                                                                           java.io.InputStream input,
                                                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.datasophon.grpc.api.GetLogRequest parseFrom(
                                                                  com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    public static com.datasophon.grpc.api.GetLogRequest parseFrom(
                                                                  com.google.protobuf.CodedInputStream input,
                                                                  com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.datasophon.grpc.api.GetLogRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder()
                : new Builder().mergeFrom(this);
    }
    
    @java.lang.Override
    protected Builder newBuilderForType(
                                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * Protobuf type {@code com.datasophon.grpc.GetLogRequest}
     */
    public static final class Builder
            extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder>
            implements
                // @@protoc_insertion_point(builder_implements:com.datasophon.grpc.GetLogRequest)
                com.datasophon.grpc.api.GetLogRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_GetLogRequest_descriptor;
        }
        
        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_GetLogRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.datasophon.grpc.api.GetLogRequest.class, com.datasophon.grpc.api.GetLogRequest.Builder.class);
        }
        
        // Construct using com.datasophon.grpc.api.GetLogRequest.newBuilder()
        private Builder() {
            
        }
        
        private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            
        }
        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            logFile_ = "";
            baseDir_ = "";
            runAsUser_ = "";
            return this;
        }
        
        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_GetLogRequest_descriptor;
        }
        
        @java.lang.Override
        public com.datasophon.grpc.api.GetLogRequest getDefaultInstanceForType() {
            return com.datasophon.grpc.api.GetLogRequest.getDefaultInstance();
        }
        
        @java.lang.Override
        public com.datasophon.grpc.api.GetLogRequest build() {
            com.datasophon.grpc.api.GetLogRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }
        
        @java.lang.Override
        public com.datasophon.grpc.api.GetLogRequest buildPartial() {
            com.datasophon.grpc.api.GetLogRequest result = new com.datasophon.grpc.api.GetLogRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }
        
        private void buildPartial0(com.datasophon.grpc.api.GetLogRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.logFile_ = logFile_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.baseDir_ = baseDir_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.runAsUser_ = runAsUser_;
            }
        }
        
        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }
        @java.lang.Override
        public Builder setField(
                                com.google.protobuf.Descriptors.FieldDescriptor field,
                                java.lang.Object value) {
            return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
                                  com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
                                  com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
                                        com.google.protobuf.Descriptors.FieldDescriptor field,
                                        int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
                                        com.google.protobuf.Descriptors.FieldDescriptor field,
                                        java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.datasophon.grpc.api.GetLogRequest) {
                return mergeFrom((com.datasophon.grpc.api.GetLogRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }
        
        public Builder mergeFrom(com.datasophon.grpc.api.GetLogRequest other) {
            if (other == com.datasophon.grpc.api.GetLogRequest.getDefaultInstance())
                return this;
            if (!other.getLogFile().isEmpty()) {
                logFile_ = other.logFile_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (!other.getBaseDir().isEmpty()) {
                baseDir_ = other.baseDir_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (!other.getRunAsUser().isEmpty()) {
                runAsUser_ = other.runAsUser_;
                bitField0_ |= 0x00000004;
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }
        
        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }
        
        @java.lang.Override
        public Builder mergeFrom(
                                 com.google.protobuf.CodedInputStream input,
                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            logFile_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            baseDir_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 26: {
                            runAsUser_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 26
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }
        private int bitField0_;
        
        private java.lang.Object logFile_ = "";
        /**
         * <code>string log_file = 1;</code>
         * @return The logFile.
         */
        public java.lang.String getLogFile() {
            java.lang.Object ref = logFile_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                logFile_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <code>string log_file = 1;</code>
         * @return The bytes for logFile.
         */
        public com.google.protobuf.ByteString getLogFileBytes() {
            java.lang.Object ref = logFile_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                logFile_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>string log_file = 1;</code>
         * @param value The logFile to set.
         * @return This builder for chaining.
         */
        public Builder setLogFile(
                                  java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            logFile_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        /**
         * <code>string log_file = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearLogFile() {
            logFile_ = getDefaultInstance().getLogFile();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }
        /**
         * <code>string log_file = 1;</code>
         * @param value The bytes for logFile to set.
         * @return This builder for chaining.
         */
        public Builder setLogFileBytes(
                                       com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            logFile_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        
        private java.lang.Object baseDir_ = "";
        /**
         * <code>string base_dir = 2;</code>
         * @return The baseDir.
         */
        public java.lang.String getBaseDir() {
            java.lang.Object ref = baseDir_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                baseDir_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <code>string base_dir = 2;</code>
         * @return The bytes for baseDir.
         */
        public com.google.protobuf.ByteString getBaseDirBytes() {
            java.lang.Object ref = baseDir_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                baseDir_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>string base_dir = 2;</code>
         * @param value The baseDir to set.
         * @return This builder for chaining.
         */
        public Builder setBaseDir(
                                  java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            baseDir_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <code>string base_dir = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearBaseDir() {
            baseDir_ = getDefaultInstance().getBaseDir();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }
        /**
         * <code>string base_dir = 2;</code>
         * @param value The bytes for baseDir to set.
         * @return This builder for chaining.
         */
        public Builder setBaseDirBytes(
                                       com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            baseDir_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        
        private java.lang.Object runAsUser_ = "";
        /**
         * <code>string run_as_user = 3;</code>
         * @return The runAsUser.
         */
        public java.lang.String getRunAsUser() {
            java.lang.Object ref = runAsUser_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                runAsUser_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <code>string run_as_user = 3;</code>
         * @return The bytes for runAsUser.
         */
        public com.google.protobuf.ByteString getRunAsUserBytes() {
            java.lang.Object ref = runAsUser_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                runAsUser_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>string run_as_user = 3;</code>
         * @param value The runAsUser to set.
         * @return This builder for chaining.
         */
        public Builder setRunAsUser(
                                    java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            runAsUser_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }
        /**
         * <code>string run_as_user = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearRunAsUser() {
            runAsUser_ = getDefaultInstance().getRunAsUser();
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }
        /**
         * <code>string run_as_user = 3;</code>
         * @param value The bytes for runAsUser to set.
         * @return This builder for chaining.
         */
        public Builder setRunAsUserBytes(
                                         com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            runAsUser_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
                                              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }
        
        @java.lang.Override
        public final Builder mergeUnknownFields(
                                                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        
        // @@protoc_insertion_point(builder_scope:com.datasophon.grpc.GetLogRequest)
    }
    
    // @@protoc_insertion_point(class_scope:com.datasophon.grpc.GetLogRequest)
    private static final com.datasophon.grpc.api.GetLogRequest DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new com.datasophon.grpc.api.GetLogRequest();
    }
    
    public static com.datasophon.grpc.api.GetLogRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }
    
    private static final com.google.protobuf.Parser<GetLogRequest> PARSER = new com.google.protobuf.AbstractParser<GetLogRequest>() {
        @java.lang.Override
        public GetLogRequest parsePartialFrom(
                                              com.google.protobuf.CodedInputStream input,
                                              com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };
    
    public static com.google.protobuf.Parser<GetLogRequest> parser() {
        return PARSER;
    }
    
    @java.lang.Override
    public com.google.protobuf.Parser<GetLogRequest> getParserForType() {
        return PARSER;
    }
    
    @java.lang.Override
    public com.datasophon.grpc.api.GetLogRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
    
}
