// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

/**
 * Protobuf type {@code com.datasophon.grpc.OlapRegistrationRequest}
 */
public final class OlapRegistrationRequest
        extends
            com.google.protobuf.GeneratedMessageV3
        implements
            // @@protoc_insertion_point(message_implements:com.datasophon.grpc.OlapRegistrationRequest)
            OlapRegistrationRequestOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use OlapRegistrationRequest.newBuilder() to construct.
    private OlapRegistrationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }
    private OlapRegistrationRequest() {
        feMaster_ = "";
        hostname_ = "";
        nodeType_ = 0;
        rootPassword_ = "";
    }
    
    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
                                           UnusedPrivateParameter unused) {
        return new OlapRegistrationRequest();
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.datasophon.grpc.api.MasterProto.internal_static_com_datasophon_grpc_OlapRegistrationRequest_descriptor;
    }
    
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.datasophon.grpc.api.MasterProto.internal_static_com_datasophon_grpc_OlapRegistrationRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.datasophon.grpc.api.OlapRegistrationRequest.class, com.datasophon.grpc.api.OlapRegistrationRequest.Builder.class);
    }
    
    public static final int FE_MASTER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object feMaster_ = "";
    /**
     * <pre>
     * FE Leader 主机名
     * </pre>
     *
     * <code>string fe_master = 1;</code>
     * @return The feMaster.
     */
    @java.lang.Override
    public java.lang.String getFeMaster() {
        java.lang.Object ref = feMaster_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            feMaster_ = s;
            return s;
        }
    }
    /**
     * <pre>
     * FE Leader 主机名
     * </pre>
     *
     * <code>string fe_master = 1;</code>
     * @return The bytes for feMaster.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFeMasterBytes() {
        java.lang.Object ref = feMaster_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            feMaster_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int HOSTNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object hostname_ = "";
    /**
     * <pre>
     * 新节点主机名
     * </pre>
     *
     * <code>string hostname = 2;</code>
     * @return The hostname.
     */
    @java.lang.Override
    public java.lang.String getHostname() {
        java.lang.Object ref = hostname_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            hostname_ = s;
            return s;
        }
    }
    /**
     * <pre>
     * 新节点主机名
     * </pre>
     *
     * <code>string hostname = 2;</code>
     * @return The bytes for hostname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHostnameBytes() {
        java.lang.Object ref = hostname_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            hostname_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    public static final int NODE_TYPE_FIELD_NUMBER = 3;
    private int nodeType_ = 0;
    /**
     * <pre>
     * 节点类型
     * </pre>
     *
     * <code>.com.datasophon.grpc.OlapNodeType node_type = 3;</code>
     * @return The enum numeric value on the wire for nodeType.
     */
    @java.lang.Override
    public int getNodeTypeValue() {
        return nodeType_;
    }
    /**
     * <pre>
     * 节点类型
     * </pre>
     *
     * <code>.com.datasophon.grpc.OlapNodeType node_type = 3;</code>
     * @return The nodeType.
     */
    @java.lang.Override
    public com.datasophon.grpc.api.OlapNodeType getNodeType() {
        com.datasophon.grpc.api.OlapNodeType result = com.datasophon.grpc.api.OlapNodeType.forNumber(nodeType_);
        return result == null ? com.datasophon.grpc.api.OlapNodeType.UNRECOGNIZED : result;
    }
    
    public static final int ROOT_PASSWORD_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rootPassword_ = "";
    /**
     * <pre>
     * Doris root 密码（Master 执行 JDBC，不落 Worker 日志）
     * </pre>
     *
     * <code>string root_password = 4;</code>
     * @return The rootPassword.
     */
    @java.lang.Override
    public java.lang.String getRootPassword() {
        java.lang.Object ref = rootPassword_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            rootPassword_ = s;
            return s;
        }
    }
    /**
     * <pre>
     * Doris root 密码（Master 执行 JDBC，不落 Worker 日志）
     * </pre>
     *
     * <code>string root_password = 4;</code>
     * @return The bytes for rootPassword.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRootPasswordBytes() {
        java.lang.Object ref = rootPassword_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            rootPassword_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }
    
    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;
        
        memoizedIsInitialized = 1;
        return true;
    }
    
    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(feMaster_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, feMaster_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostname_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hostname_);
        }
        if (nodeType_ != com.datasophon.grpc.api.OlapNodeType.OLAP_NODE_TYPE_UNSPECIFIED.getNumber()) {
            output.writeEnum(3, nodeType_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootPassword_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, rootPassword_);
        }
        getUnknownFields().writeTo(output);
    }
    
    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;
        
        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(feMaster_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, feMaster_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostname_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hostname_);
        }
        if (nodeType_ != com.datasophon.grpc.api.OlapNodeType.OLAP_NODE_TYPE_UNSPECIFIED.getNumber()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeEnumSize(3, nodeType_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootPassword_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, rootPassword_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.datasophon.grpc.api.OlapRegistrationRequest)) {
            return super.equals(obj);
        }
        com.datasophon.grpc.api.OlapRegistrationRequest other = (com.datasophon.grpc.api.OlapRegistrationRequest) obj;
        
        if (!getFeMaster()
                .equals(other.getFeMaster()))
            return false;
        if (!getHostname()
                .equals(other.getHostname()))
            return false;
        if (nodeType_ != other.nodeType_)
            return false;
        if (!getRootPassword()
                .equals(other.getRootPassword()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }
    
    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + FE_MASTER_FIELD_NUMBER;
        hash = (53 * hash) + getFeMaster().hashCode();
        hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getHostname().hashCode();
        hash = (37 * hash) + NODE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + nodeType_;
        hash = (37 * hash) + ROOT_PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getRootPassword().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }
    
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseFrom(
                                                                            java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseFrom(
                                                                            java.nio.ByteBuffer data,
                                                                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseFrom(
                                                                            com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseFrom(
                                                                            com.google.protobuf.ByteString data,
                                                                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseFrom(
                                                                            byte[] data,
                                                                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseFrom(
                                                                            java.io.InputStream input,
                                                                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }
    
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseDelimitedFrom(
                                                                                     java.io.InputStream input,
                                                                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseFrom(
                                                                            com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    public static com.datasophon.grpc.api.OlapRegistrationRequest parseFrom(
                                                                            com.google.protobuf.CodedInputStream input,
                                                                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    
    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.datasophon.grpc.api.OlapRegistrationRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder()
                : new Builder().mergeFrom(this);
    }
    
    @java.lang.Override
    protected Builder newBuilderForType(
                                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * Protobuf type {@code com.datasophon.grpc.OlapRegistrationRequest}
     */
    public static final class Builder
            extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder>
            implements
                // @@protoc_insertion_point(builder_implements:com.datasophon.grpc.OlapRegistrationRequest)
                com.datasophon.grpc.api.OlapRegistrationRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.datasophon.grpc.api.MasterProto.internal_static_com_datasophon_grpc_OlapRegistrationRequest_descriptor;
        }
        
        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.datasophon.grpc.api.MasterProto.internal_static_com_datasophon_grpc_OlapRegistrationRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.datasophon.grpc.api.OlapRegistrationRequest.class, com.datasophon.grpc.api.OlapRegistrationRequest.Builder.class);
        }
        
        // Construct using com.datasophon.grpc.api.OlapRegistrationRequest.newBuilder()
        private Builder() {
            
        }
        
        private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            
        }
        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            feMaster_ = "";
            hostname_ = "";
            nodeType_ = 0;
            rootPassword_ = "";
            return this;
        }
        
        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.datasophon.grpc.api.MasterProto.internal_static_com_datasophon_grpc_OlapRegistrationRequest_descriptor;
        }
        
        @java.lang.Override
        public com.datasophon.grpc.api.OlapRegistrationRequest getDefaultInstanceForType() {
            return com.datasophon.grpc.api.OlapRegistrationRequest.getDefaultInstance();
        }
        
        @java.lang.Override
        public com.datasophon.grpc.api.OlapRegistrationRequest build() {
            com.datasophon.grpc.api.OlapRegistrationRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }
        
        @java.lang.Override
        public com.datasophon.grpc.api.OlapRegistrationRequest buildPartial() {
            com.datasophon.grpc.api.OlapRegistrationRequest result = new com.datasophon.grpc.api.OlapRegistrationRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }
        
        private void buildPartial0(com.datasophon.grpc.api.OlapRegistrationRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.feMaster_ = feMaster_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.hostname_ = hostname_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.nodeType_ = nodeType_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.rootPassword_ = rootPassword_;
            }
        }
        
        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }
        @java.lang.Override
        public Builder setField(
                                com.google.protobuf.Descriptors.FieldDescriptor field,
                                java.lang.Object value) {
            return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
                                  com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
                                  com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
                                        com.google.protobuf.Descriptors.FieldDescriptor field,
                                        int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
                                        com.google.protobuf.Descriptors.FieldDescriptor field,
                                        java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.datasophon.grpc.api.OlapRegistrationRequest) {
                return mergeFrom((com.datasophon.grpc.api.OlapRegistrationRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }
        
        public Builder mergeFrom(com.datasophon.grpc.api.OlapRegistrationRequest other) {
            if (other == com.datasophon.grpc.api.OlapRegistrationRequest.getDefaultInstance())
                return this;
            if (!other.getFeMaster().isEmpty()) {
                feMaster_ = other.feMaster_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (!other.getHostname().isEmpty()) {
                hostname_ = other.hostname_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (other.nodeType_ != 0) {
                setNodeTypeValue(other.getNodeTypeValue());
            }
            if (!other.getRootPassword().isEmpty()) {
                rootPassword_ = other.rootPassword_;
                bitField0_ |= 0x00000008;
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }
        
        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }
        
        @java.lang.Override
        public Builder mergeFrom(
                                 com.google.protobuf.CodedInputStream input,
                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            feMaster_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            hostname_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 24: {
                            nodeType_ = input.readEnum();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 24
                        case 34: {
                            rootPassword_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 34
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }
        private int bitField0_;
        
        private java.lang.Object feMaster_ = "";
        /**
         * <pre>
         * FE Leader 主机名
         * </pre>
         *
         * <code>string fe_master = 1;</code>
         * @return The feMaster.
         */
        public java.lang.String getFeMaster() {
            java.lang.Object ref = feMaster_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                feMaster_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <pre>
         * FE Leader 主机名
         * </pre>
         *
         * <code>string fe_master = 1;</code>
         * @return The bytes for feMaster.
         */
        public com.google.protobuf.ByteString getFeMasterBytes() {
            java.lang.Object ref = feMaster_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                feMaster_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <pre>
         * FE Leader 主机名
         * </pre>
         *
         * <code>string fe_master = 1;</code>
         * @param value The feMaster to set.
         * @return This builder for chaining.
         */
        public Builder setFeMaster(
                                   java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            feMaster_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        /**
         * <pre>
         * FE Leader 主机名
         * </pre>
         *
         * <code>string fe_master = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearFeMaster() {
            feMaster_ = getDefaultInstance().getFeMaster();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }
        /**
         * <pre>
         * FE Leader 主机名
         * </pre>
         *
         * <code>string fe_master = 1;</code>
         * @param value The bytes for feMaster to set.
         * @return This builder for chaining.
         */
        public Builder setFeMasterBytes(
                                        com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            feMaster_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        
        private java.lang.Object hostname_ = "";
        /**
         * <pre>
         * 新节点主机名
         * </pre>
         *
         * <code>string hostname = 2;</code>
         * @return The hostname.
         */
        public java.lang.String getHostname() {
            java.lang.Object ref = hostname_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                hostname_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <pre>
         * 新节点主机名
         * </pre>
         *
         * <code>string hostname = 2;</code>
         * @return The bytes for hostname.
         */
        public com.google.protobuf.ByteString getHostnameBytes() {
            java.lang.Object ref = hostname_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                hostname_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <pre>
         * 新节点主机名
         * </pre>
         *
         * <code>string hostname = 2;</code>
         * @param value The hostname to set.
         * @return This builder for chaining.
         */
        public Builder setHostname(
                                   java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            hostname_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <pre>
         * 新节点主机名
         * </pre>
         *
         * <code>string hostname = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearHostname() {
            hostname_ = getDefaultInstance().getHostname();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }
        /**
         * <pre>
         * 新节点主机名
         * </pre>
         *
         * <code>string hostname = 2;</code>
         * @param value The bytes for hostname to set.
         * @return This builder for chaining.
         */
        public Builder setHostnameBytes(
                                        com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            hostname_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        
        private int nodeType_ = 0;
        /**
         * <pre>
         * 节点类型
         * </pre>
         *
         * <code>.com.datasophon.grpc.OlapNodeType node_type = 3;</code>
         * @return The enum numeric value on the wire for nodeType.
         */
        @java.lang.Override
        public int getNodeTypeValue() {
            return nodeType_;
        }
        /**
         * <pre>
         * 节点类型
         * </pre>
         *
         * <code>.com.datasophon.grpc.OlapNodeType node_type = 3;</code>
         * @param value The enum numeric value on the wire for nodeType to set.
         * @return This builder for chaining.
         */
        public Builder setNodeTypeValue(int value) {
            nodeType_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }
        /**
         * <pre>
         * 节点类型
         * </pre>
         *
         * <code>.com.datasophon.grpc.OlapNodeType node_type = 3;</code>
         * @return The nodeType.
         */
        @java.lang.Override
        public com.datasophon.grpc.api.OlapNodeType getNodeType() {
            com.datasophon.grpc.api.OlapNodeType result = com.datasophon.grpc.api.OlapNodeType.forNumber(nodeType_);
            return result == null ? com.datasophon.grpc.api.OlapNodeType.UNRECOGNIZED : result;
        }
        /**
         * <pre>
         * 节点类型
         * </pre>
         *
         * <code>.com.datasophon.grpc.OlapNodeType node_type = 3;</code>
         * @param value The nodeType to set.
         * @return This builder for chaining.
         */
        public Builder setNodeType(com.datasophon.grpc.api.OlapNodeType value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000004;
            nodeType_ = value.getNumber();
            onChanged();
            return this;
        }
        /**
         * <pre>
         * 节点类型
         * </pre>
         *
         * <code>.com.datasophon.grpc.OlapNodeType node_type = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearNodeType() {
            bitField0_ = (bitField0_ & ~0x00000004);
            nodeType_ = 0;
            onChanged();
            return this;
        }
        
        private java.lang.Object rootPassword_ = "";
        /**
         * <pre>
         * Doris root 密码（Master 执行 JDBC，不落 Worker 日志）
         * </pre>
         *
         * <code>string root_password = 4;</code>
         * @return The rootPassword.
         */
        public java.lang.String getRootPassword() {
            java.lang.Object ref = rootPassword_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                rootPassword_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <pre>
         * Doris root 密码（Master 执行 JDBC，不落 Worker 日志）
         * </pre>
         *
         * <code>string root_password = 4;</code>
         * @return The bytes for rootPassword.
         */
        public com.google.protobuf.ByteString getRootPasswordBytes() {
            java.lang.Object ref = rootPassword_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                rootPassword_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <pre>
         * Doris root 密码（Master 执行 JDBC，不落 Worker 日志）
         * </pre>
         *
         * <code>string root_password = 4;</code>
         * @param value The rootPassword to set.
         * @return This builder for chaining.
         */
        public Builder setRootPassword(
                                       java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            rootPassword_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }
        /**
         * <pre>
         * Doris root 密码（Master 执行 JDBC，不落 Worker 日志）
         * </pre>
         *
         * <code>string root_password = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearRootPassword() {
            rootPassword_ = getDefaultInstance().getRootPassword();
            bitField0_ = (bitField0_ & ~0x00000008);
            onChanged();
            return this;
        }
        /**
         * <pre>
         * Doris root 密码（Master 执行 JDBC，不落 Worker 日志）
         * </pre>
         *
         * <code>string root_password = 4;</code>
         * @param value The bytes for rootPassword to set.
         * @return This builder for chaining.
         */
        public Builder setRootPasswordBytes(
                                            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            rootPassword_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
                                              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }
        
        @java.lang.Override
        public final Builder mergeUnknownFields(
                                                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        
        // @@protoc_insertion_point(builder_scope:com.datasophon.grpc.OlapRegistrationRequest)
    }
    
    // @@protoc_insertion_point(class_scope:com.datasophon.grpc.OlapRegistrationRequest)
    private static final com.datasophon.grpc.api.OlapRegistrationRequest DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new com.datasophon.grpc.api.OlapRegistrationRequest();
    }
    
    public static com.datasophon.grpc.api.OlapRegistrationRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }
    
    private static final com.google.protobuf.Parser<OlapRegistrationRequest> PARSER = new com.google.protobuf.AbstractParser<OlapRegistrationRequest>() {
        @java.lang.Override
        public OlapRegistrationRequest parsePartialFrom(
                                                        com.google.protobuf.CodedInputStream input,
                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };
    
    public static com.google.protobuf.Parser<OlapRegistrationRequest> parser() {
        return PARSER;
    }
    
    @java.lang.Override
    public com.google.protobuf.Parser<OlapRegistrationRequest> getParserForType() {
        return PARSER;
    }
    
    @java.lang.Override
    public com.datasophon.grpc.api.OlapRegistrationRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
    
}
