// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registry.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

/**
 * Protobuf type {@code com.datasophon.grpc.RegisterRequest}
 */
public final class RegisterRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.datasophon.grpc.RegisterRequest)
    RegisterRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterRequest.newBuilder() to construct.
  private RegisterRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterRequest() {
    hostname_ = "";
    cpuArchitecture_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RegisterRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.datasophon.grpc.api.RegistryProto.internal_static_com_datasophon_grpc_RegisterRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.datasophon.grpc.api.RegistryProto.internal_static_com_datasophon_grpc_RegisterRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.datasophon.grpc.api.RegisterRequest.class, com.datasophon.grpc.api.RegisterRequest.Builder.class);
  }

  public static final int HOSTNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hostname_ = "";
  /**
   * <pre>
   * worker 主机名，作为唯一标识
   * </pre>
   *
   * <code>string hostname = 1;</code>
   * @return The hostname.
   */
  @java.lang.Override
  public java.lang.String getHostname() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostname_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * worker 主机名，作为唯一标识
   * </pre>
   *
   * <code>string hostname = 1;</code>
   * @return The bytes for hostname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostnameBytes() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GRPC_PORT_FIELD_NUMBER = 2;
  private int grpcPort_ = 0;
  /**
   * <pre>
   * worker gRPC server 监听端口（默认 18082）
   * </pre>
   *
   * <code>int32 grpc_port = 2;</code>
   * @return The grpcPort.
   */
  @java.lang.Override
  public int getGrpcPort() {
    return grpcPort_;
  }

  public static final int CPU_ARCHITECTURE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object cpuArchitecture_ = "";
  /**
   * <pre>
   * x86_64 / aarch64
   * </pre>
   *
   * <code>string cpu_architecture = 3;</code>
   * @return The cpuArchitecture.
   */
  @java.lang.Override
  public java.lang.String getCpuArchitecture() {
    java.lang.Object ref = cpuArchitecture_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cpuArchitecture_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * x86_64 / aarch64
   * </pre>
   *
   * <code>string cpu_architecture = 3;</code>
   * @return The bytes for cpuArchitecture.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCpuArchitectureBytes() {
    java.lang.Object ref = cpuArchitecture_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cpuArchitecture_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTER_ID_FIELD_NUMBER = 4;
  private int clusterId_ = 0;
  /**
   * <pre>
   * 所属集群 ID
   * </pre>
   *
   * <code>int32 cluster_id = 4;</code>
   * @return The clusterId.
   */
  @java.lang.Override
  public int getClusterId() {
    return clusterId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostname_);
    }
    if (grpcPort_ != 0) {
      output.writeInt32(2, grpcPort_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cpuArchitecture_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cpuArchitecture_);
    }
    if (clusterId_ != 0) {
      output.writeInt32(4, clusterId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostname_);
    }
    if (grpcPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, grpcPort_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cpuArchitecture_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cpuArchitecture_);
    }
    if (clusterId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, clusterId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.datasophon.grpc.api.RegisterRequest)) {
      return super.equals(obj);
    }
    com.datasophon.grpc.api.RegisterRequest other = (com.datasophon.grpc.api.RegisterRequest) obj;

    if (!getHostname()
        .equals(other.getHostname())) return false;
    if (getGrpcPort()
        != other.getGrpcPort()) return false;
    if (!getCpuArchitecture()
        .equals(other.getCpuArchitecture())) return false;
    if (getClusterId()
        != other.getClusterId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostname().hashCode();
    hash = (37 * hash) + GRPC_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getGrpcPort();
    hash = (37 * hash) + CPU_ARCHITECTURE_FIELD_NUMBER;
    hash = (53 * hash) + getCpuArchitecture().hashCode();
    hash = (37 * hash) + CLUSTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClusterId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.datasophon.grpc.api.RegisterRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.RegisterRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.RegisterRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.RegisterRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.RegisterRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.RegisterRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.RegisterRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.datasophon.grpc.api.RegisterRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.datasophon.grpc.api.RegisterRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.datasophon.grpc.api.RegisterRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.datasophon.grpc.api.RegisterRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.datasophon.grpc.api.RegisterRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.datasophon.grpc.api.RegisterRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.datasophon.grpc.RegisterRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.datasophon.grpc.RegisterRequest)
      com.datasophon.grpc.api.RegisterRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.datasophon.grpc.api.RegistryProto.internal_static_com_datasophon_grpc_RegisterRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.datasophon.grpc.api.RegistryProto.internal_static_com_datasophon_grpc_RegisterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.datasophon.grpc.api.RegisterRequest.class, com.datasophon.grpc.api.RegisterRequest.Builder.class);
    }

    // Construct using com.datasophon.grpc.api.RegisterRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hostname_ = "";
      grpcPort_ = 0;
      cpuArchitecture_ = "";
      clusterId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.datasophon.grpc.api.RegistryProto.internal_static_com_datasophon_grpc_RegisterRequest_descriptor;
    }

    @java.lang.Override
    public com.datasophon.grpc.api.RegisterRequest getDefaultInstanceForType() {
      return com.datasophon.grpc.api.RegisterRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.datasophon.grpc.api.RegisterRequest build() {
      com.datasophon.grpc.api.RegisterRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.datasophon.grpc.api.RegisterRequest buildPartial() {
      com.datasophon.grpc.api.RegisterRequest result = new com.datasophon.grpc.api.RegisterRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.datasophon.grpc.api.RegisterRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hostname_ = hostname_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.grpcPort_ = grpcPort_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cpuArchitecture_ = cpuArchitecture_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.clusterId_ = clusterId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.datasophon.grpc.api.RegisterRequest) {
        return mergeFrom((com.datasophon.grpc.api.RegisterRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.datasophon.grpc.api.RegisterRequest other) {
      if (other == com.datasophon.grpc.api.RegisterRequest.getDefaultInstance()) return this;
      if (!other.getHostname().isEmpty()) {
        hostname_ = other.hostname_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getGrpcPort() != 0) {
        setGrpcPort(other.getGrpcPort());
      }
      if (!other.getCpuArchitecture().isEmpty()) {
        cpuArchitecture_ = other.cpuArchitecture_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getClusterId() != 0) {
        setClusterId(other.getClusterId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              hostname_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              grpcPort_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              cpuArchitecture_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              clusterId_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object hostname_ = "";
    /**
     * <pre>
     * worker 主机名，作为唯一标识
     * </pre>
     *
     * <code>string hostname = 1;</code>
     * @return The hostname.
     */
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * worker 主机名，作为唯一标识
     * </pre>
     *
     * <code>string hostname = 1;</code>
     * @return The bytes for hostname.
     */
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * worker 主机名，作为唯一标识
     * </pre>
     *
     * <code>string hostname = 1;</code>
     * @param value The hostname to set.
     * @return This builder for chaining.
     */
    public Builder setHostname(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hostname_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * worker 主机名，作为唯一标识
     * </pre>
     *
     * <code>string hostname = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostname() {
      hostname_ = getDefaultInstance().getHostname();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * worker 主机名，作为唯一标识
     * </pre>
     *
     * <code>string hostname = 1;</code>
     * @param value The bytes for hostname to set.
     * @return This builder for chaining.
     */
    public Builder setHostnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hostname_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int grpcPort_ ;
    /**
     * <pre>
     * worker gRPC server 监听端口（默认 18082）
     * </pre>
     *
     * <code>int32 grpc_port = 2;</code>
     * @return The grpcPort.
     */
    @java.lang.Override
    public int getGrpcPort() {
      return grpcPort_;
    }
    /**
     * <pre>
     * worker gRPC server 监听端口（默认 18082）
     * </pre>
     *
     * <code>int32 grpc_port = 2;</code>
     * @param value The grpcPort to set.
     * @return This builder for chaining.
     */
    public Builder setGrpcPort(int value) {

      grpcPort_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * worker gRPC server 监听端口（默认 18082）
     * </pre>
     *
     * <code>int32 grpc_port = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGrpcPort() {
      bitField0_ = (bitField0_ & ~0x00000002);
      grpcPort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object cpuArchitecture_ = "";
    /**
     * <pre>
     * x86_64 / aarch64
     * </pre>
     *
     * <code>string cpu_architecture = 3;</code>
     * @return The cpuArchitecture.
     */
    public java.lang.String getCpuArchitecture() {
      java.lang.Object ref = cpuArchitecture_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpuArchitecture_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * x86_64 / aarch64
     * </pre>
     *
     * <code>string cpu_architecture = 3;</code>
     * @return The bytes for cpuArchitecture.
     */
    public com.google.protobuf.ByteString
        getCpuArchitectureBytes() {
      java.lang.Object ref = cpuArchitecture_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpuArchitecture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * x86_64 / aarch64
     * </pre>
     *
     * <code>string cpu_architecture = 3;</code>
     * @param value The cpuArchitecture to set.
     * @return This builder for chaining.
     */
    public Builder setCpuArchitecture(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      cpuArchitecture_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * x86_64 / aarch64
     * </pre>
     *
     * <code>string cpu_architecture = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpuArchitecture() {
      cpuArchitecture_ = getDefaultInstance().getCpuArchitecture();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * x86_64 / aarch64
     * </pre>
     *
     * <code>string cpu_architecture = 3;</code>
     * @param value The bytes for cpuArchitecture to set.
     * @return This builder for chaining.
     */
    public Builder setCpuArchitectureBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      cpuArchitecture_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int clusterId_ ;
    /**
     * <pre>
     * 所属集群 ID
     * </pre>
     *
     * <code>int32 cluster_id = 4;</code>
     * @return The clusterId.
     */
    @java.lang.Override
    public int getClusterId() {
      return clusterId_;
    }
    /**
     * <pre>
     * 所属集群 ID
     * </pre>
     *
     * <code>int32 cluster_id = 4;</code>
     * @param value The clusterId to set.
     * @return This builder for chaining.
     */
    public Builder setClusterId(int value) {

      clusterId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 所属集群 ID
     * </pre>
     *
     * <code>int32 cluster_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      clusterId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.datasophon.grpc.RegisterRequest)
  }

  // @@protoc_insertion_point(class_scope:com.datasophon.grpc.RegisterRequest)
  private static final com.datasophon.grpc.api.RegisterRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.datasophon.grpc.api.RegisterRequest();
  }

  public static com.datasophon.grpc.api.RegisterRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterRequest>
      PARSER = new com.google.protobuf.AbstractParser<RegisterRequest>() {
    @java.lang.Override
    public RegisterRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RegisterRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.datasophon.grpc.api.RegisterRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

