// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

public interface ServiceRoleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.datasophon.grpc.ServiceRoleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_name = 1;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 1;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string service_role_name = 2;</code>
   * @return The serviceRoleName.
   */
  java.lang.String getServiceRoleName();
  /**
   * <code>string service_role_name = 2;</code>
   * @return The bytes for serviceRoleName.
   */
  com.google.protobuf.ByteString
      getServiceRoleNameBytes();

  /**
   * <code>string json_payload = 3;</code>
   * @return The jsonPayload.
   */
  java.lang.String getJsonPayload();
  /**
   * <code>string json_payload = 3;</code>
   * @return The bytes for jsonPayload.
   */
  com.google.protobuf.ByteString
      getJsonPayloadBytes();

  /**
   * <code>string config_map_json = 4;</code>
   * @return The configMapJson.
   */
  java.lang.String getConfigMapJson();
  /**
   * <code>string config_map_json = 4;</code>
   * @return The bytes for configMapJson.
   */
  com.google.protobuf.ByteString
      getConfigMapJsonBytes();
}
