// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

/**
 * <pre>
 **
 * Phase 2：服务角色操作通用请求。
 *
 * json_payload    = Jackson 序列化的命令 POJO（cofigFileMap 字段置 null）
 * config_map_json = cofigFileMap 序列化为 List&amp;lt;ConfigFileEntry&amp;gt; 的 JSON
 *                   （仅 ConfigureServiceRole / InstallServiceRole 使用）
 * </pre>
 *
 * Protobuf type {@code com.datasophon.grpc.ServiceRoleRequest}
 */
public final class ServiceRoleRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.datasophon.grpc.ServiceRoleRequest)
    ServiceRoleRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServiceRoleRequest.newBuilder() to construct.
  private ServiceRoleRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServiceRoleRequest() {
    serviceName_ = "";
    serviceRoleName_ = "";
    jsonPayload_ = "";
    configMapJson_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServiceRoleRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_ServiceRoleRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_ServiceRoleRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.datasophon.grpc.api.ServiceRoleRequest.class, com.datasophon.grpc.api.ServiceRoleRequest.Builder.class);
  }

  public static final int SERVICE_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serviceName_ = "";
  /**
   * <code>string service_name = 1;</code>
   * @return The serviceName.
   */
  @java.lang.Override
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <code>string service_name = 1;</code>
   * @return The bytes for serviceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICE_ROLE_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serviceRoleName_ = "";
  /**
   * <code>string service_role_name = 2;</code>
   * @return The serviceRoleName.
   */
  @java.lang.Override
  public java.lang.String getServiceRoleName() {
    java.lang.Object ref = serviceRoleName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceRoleName_ = s;
      return s;
    }
  }
  /**
   * <code>string service_role_name = 2;</code>
   * @return The bytes for serviceRoleName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceRoleNameBytes() {
    java.lang.Object ref = serviceRoleName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceRoleName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JSON_PAYLOAD_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jsonPayload_ = "";
  /**
   * <code>string json_payload = 3;</code>
   * @return The jsonPayload.
   */
  @java.lang.Override
  public java.lang.String getJsonPayload() {
    java.lang.Object ref = jsonPayload_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jsonPayload_ = s;
      return s;
    }
  }
  /**
   * <code>string json_payload = 3;</code>
   * @return The bytes for jsonPayload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJsonPayloadBytes() {
    java.lang.Object ref = jsonPayload_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jsonPayload_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIG_MAP_JSON_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object configMapJson_ = "";
  /**
   * <code>string config_map_json = 4;</code>
   * @return The configMapJson.
   */
  @java.lang.Override
  public java.lang.String getConfigMapJson() {
    java.lang.Object ref = configMapJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      configMapJson_ = s;
      return s;
    }
  }
  /**
   * <code>string config_map_json = 4;</code>
   * @return The bytes for configMapJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConfigMapJsonBytes() {
    java.lang.Object ref = configMapJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      configMapJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceRoleName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceRoleName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonPayload_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jsonPayload_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(configMapJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, configMapJson_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceRoleName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceRoleName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonPayload_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jsonPayload_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(configMapJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, configMapJson_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.datasophon.grpc.api.ServiceRoleRequest)) {
      return super.equals(obj);
    }
    com.datasophon.grpc.api.ServiceRoleRequest other = (com.datasophon.grpc.api.ServiceRoleRequest) obj;

    if (!getServiceName()
        .equals(other.getServiceName())) return false;
    if (!getServiceRoleName()
        .equals(other.getServiceRoleName())) return false;
    if (!getJsonPayload()
        .equals(other.getJsonPayload())) return false;
    if (!getConfigMapJson()
        .equals(other.getConfigMapJson())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + SERVICE_ROLE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceRoleName().hashCode();
    hash = (37 * hash) + JSON_PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getJsonPayload().hashCode();
    hash = (37 * hash) + CONFIG_MAP_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getConfigMapJson().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.datasophon.grpc.api.ServiceRoleRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.ServiceRoleRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.ServiceRoleRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.ServiceRoleRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.ServiceRoleRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.datasophon.grpc.api.ServiceRoleRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.datasophon.grpc.api.ServiceRoleRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.datasophon.grpc.api.ServiceRoleRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.datasophon.grpc.api.ServiceRoleRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.datasophon.grpc.api.ServiceRoleRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.datasophon.grpc.api.ServiceRoleRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.datasophon.grpc.api.ServiceRoleRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.datasophon.grpc.api.ServiceRoleRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Phase 2：服务角色操作通用请求。
   *
   * json_payload    = Jackson 序列化的命令 POJO（cofigFileMap 字段置 null）
   * config_map_json = cofigFileMap 序列化为 List&amp;lt;ConfigFileEntry&amp;gt; 的 JSON
   *                   （仅 ConfigureServiceRole / InstallServiceRole 使用）
   * </pre>
   *
   * Protobuf type {@code com.datasophon.grpc.ServiceRoleRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.datasophon.grpc.ServiceRoleRequest)
      com.datasophon.grpc.api.ServiceRoleRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_ServiceRoleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_ServiceRoleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.datasophon.grpc.api.ServiceRoleRequest.class, com.datasophon.grpc.api.ServiceRoleRequest.Builder.class);
    }

    // Construct using com.datasophon.grpc.api.ServiceRoleRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      serviceName_ = "";
      serviceRoleName_ = "";
      jsonPayload_ = "";
      configMapJson_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.datasophon.grpc.api.WorkerProto.internal_static_com_datasophon_grpc_ServiceRoleRequest_descriptor;
    }

    @java.lang.Override
    public com.datasophon.grpc.api.ServiceRoleRequest getDefaultInstanceForType() {
      return com.datasophon.grpc.api.ServiceRoleRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.datasophon.grpc.api.ServiceRoleRequest build() {
      com.datasophon.grpc.api.ServiceRoleRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.datasophon.grpc.api.ServiceRoleRequest buildPartial() {
      com.datasophon.grpc.api.ServiceRoleRequest result = new com.datasophon.grpc.api.ServiceRoleRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.datasophon.grpc.api.ServiceRoleRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.serviceName_ = serviceName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.serviceRoleName_ = serviceRoleName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.jsonPayload_ = jsonPayload_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.configMapJson_ = configMapJson_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.datasophon.grpc.api.ServiceRoleRequest) {
        return mergeFrom((com.datasophon.grpc.api.ServiceRoleRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.datasophon.grpc.api.ServiceRoleRequest other) {
      if (other == com.datasophon.grpc.api.ServiceRoleRequest.getDefaultInstance()) return this;
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getServiceRoleName().isEmpty()) {
        serviceRoleName_ = other.serviceRoleName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getJsonPayload().isEmpty()) {
        jsonPayload_ = other.jsonPayload_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getConfigMapJson().isEmpty()) {
        configMapJson_ = other.configMapJson_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              serviceName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              serviceRoleName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              jsonPayload_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              configMapJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object serviceName_ = "";
    /**
     * <code>string service_name = 1;</code>
     * @return The serviceName.
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service_name = 1;</code>
     * @return The bytes for serviceName.
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service_name = 1;</code>
     * @param value The serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serviceName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string service_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceName() {
      serviceName_ = getDefaultInstance().getServiceName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string service_name = 1;</code>
     * @param value The bytes for serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serviceName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object serviceRoleName_ = "";
    /**
     * <code>string service_role_name = 2;</code>
     * @return The serviceRoleName.
     */
    public java.lang.String getServiceRoleName() {
      java.lang.Object ref = serviceRoleName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceRoleName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service_role_name = 2;</code>
     * @return The bytes for serviceRoleName.
     */
    public com.google.protobuf.ByteString
        getServiceRoleNameBytes() {
      java.lang.Object ref = serviceRoleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceRoleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service_role_name = 2;</code>
     * @param value The serviceRoleName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceRoleName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serviceRoleName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string service_role_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceRoleName() {
      serviceRoleName_ = getDefaultInstance().getServiceRoleName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string service_role_name = 2;</code>
     * @param value The bytes for serviceRoleName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceRoleNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serviceRoleName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object jsonPayload_ = "";
    /**
     * <code>string json_payload = 3;</code>
     * @return The jsonPayload.
     */
    public java.lang.String getJsonPayload() {
      java.lang.Object ref = jsonPayload_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonPayload_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string json_payload = 3;</code>
     * @return The bytes for jsonPayload.
     */
    public com.google.protobuf.ByteString
        getJsonPayloadBytes() {
      java.lang.Object ref = jsonPayload_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonPayload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string json_payload = 3;</code>
     * @param value The jsonPayload to set.
     * @return This builder for chaining.
     */
    public Builder setJsonPayload(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jsonPayload_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string json_payload = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsonPayload() {
      jsonPayload_ = getDefaultInstance().getJsonPayload();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string json_payload = 3;</code>
     * @param value The bytes for jsonPayload to set.
     * @return This builder for chaining.
     */
    public Builder setJsonPayloadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jsonPayload_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object configMapJson_ = "";
    /**
     * <code>string config_map_json = 4;</code>
     * @return The configMapJson.
     */
    public java.lang.String getConfigMapJson() {
      java.lang.Object ref = configMapJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        configMapJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string config_map_json = 4;</code>
     * @return The bytes for configMapJson.
     */
    public com.google.protobuf.ByteString
        getConfigMapJsonBytes() {
      java.lang.Object ref = configMapJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        configMapJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string config_map_json = 4;</code>
     * @param value The configMapJson to set.
     * @return This builder for chaining.
     */
    public Builder setConfigMapJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      configMapJson_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string config_map_json = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfigMapJson() {
      configMapJson_ = getDefaultInstance().getConfigMapJson();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string config_map_json = 4;</code>
     * @param value The bytes for configMapJson to set.
     * @return This builder for chaining.
     */
    public Builder setConfigMapJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      configMapJson_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.datasophon.grpc.ServiceRoleRequest)
  }

  // @@protoc_insertion_point(class_scope:com.datasophon.grpc.ServiceRoleRequest)
  private static final com.datasophon.grpc.api.ServiceRoleRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.datasophon.grpc.api.ServiceRoleRequest();
  }

  public static com.datasophon.grpc.api.ServiceRoleRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServiceRoleRequest>
      PARSER = new com.google.protobuf.AbstractParser<ServiceRoleRequest>() {
    @java.lang.Override
    public ServiceRoleRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServiceRoleRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceRoleRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.datasophon.grpc.api.ServiceRoleRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

