// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

public interface UnixUserRequestOrBuilder
        extends
            // @@protoc_insertion_point(interface_extends:com.datasophon.grpc.UnixUserRequest)
            com.google.protobuf.MessageOrBuilder {
    
    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString getUsernameBytes();
    
    /**
     * <code>string main_group = 2;</code>
     * @return The mainGroup.
     */
    java.lang.String getMainGroup();
    /**
     * <code>string main_group = 2;</code>
     * @return The bytes for mainGroup.
     */
    com.google.protobuf.ByteString getMainGroupBytes();
    
    /**
     * <code>string other_groups = 3;</code>
     * @return The otherGroups.
     */
    java.lang.String getOtherGroups();
    /**
     * <code>string other_groups = 3;</code>
     * @return The bytes for otherGroups.
     */
    com.google.protobuf.ByteString getOtherGroupsBytes();
}
