// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

public interface UnixGroupRequestOrBuilder
        extends
            // @@protoc_insertion_point(interface_extends:com.datasophon.grpc.UnixGroupRequest)
            com.google.protobuf.MessageOrBuilder {
    
    /**
     * <code>string group_name = 1;</code>
     * @return The groupName.
     */
    java.lang.String getGroupName();
    /**
     * <code>string group_name = 1;</code>
     * @return The bytes for groupName.
     */
    com.google.protobuf.ByteString getGroupNameBytes();
}
