// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

public final class WorkerProto {
  private WorkerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_ExecuteCmdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_GetLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_GetLogRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014worker.proto\022\023com.datasophon.grpc\032\014com" +
      "mon.proto\"\036\n\013PingRequest\022\017\n\007message\030\001 \001(" +
      "\t\";\n\021ExecuteCmdRequest\022\020\n\010commands\030\001 \003(\t" +
      "\022\024\n\014command_line\030\002 \001(\t\"H\n\rGetLogRequest\022" +
      "\020\n\010log_file\030\001 \001(\t\022\020\n\010base_dir\030\002 \001(\t\022\023\n\013r" +
      "un_as_user\030\003 \001(\t2\215\002\n\024WorkerCommandServic" +
      "e\022K\n\004Ping\022 .com.datasophon.grpc.PingRequ" +
      "est\032!.com.datasophon.grpc.ExecResultPb\022W" +
      "\n\nExecuteCmd\022&.com.datasophon.grpc.Execu" +
      "teCmdRequest\032!.com.datasophon.grpc.ExecR" +
      "esultPb\022O\n\006GetLog\022\".com.datasophon.grpc." +
      "GetLogRequest\032!.com.datasophon.grpc.Exec" +
      "ResultPbB(\n\027com.datasophon.grpc.apiB\013Wor" +
      "kerProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.datasophon.grpc.api.CommonProto.getDescriptor(),
        });
    internal_static_com_datasophon_grpc_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_datasophon_grpc_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_PingRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_datasophon_grpc_ExecuteCmdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor,
        new java.lang.String[] { "Commands", "CommandLine", });
    internal_static_com_datasophon_grpc_GetLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_datasophon_grpc_GetLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_GetLogRequest_descriptor,
        new java.lang.String[] { "LogFile", "BaseDir", "RunAsUser", });
    com.datasophon.grpc.api.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
