// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

public final class WorkerProto {
  private WorkerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_ExecuteCmdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_GetLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_GetLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_ServiceRoleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_ServiceRoleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_UnixGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_UnixGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_UnixUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_UnixUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_FileOperateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_FileOperateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_AlertConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_AlertConfigRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014worker.proto\022\023com.datasophon.grpc\032\014com" +
      "mon.proto\"\036\n\013PingRequest\022\017\n\007message\030\001 \001(" +
      "\t\";\n\021ExecuteCmdRequest\022\020\n\010commands\030\001 \003(\t" +
      "\022\024\n\014command_line\030\002 \001(\t\"H\n\rGetLogRequest\022" +
      "\020\n\010log_file\030\001 \001(\t\022\020\n\010base_dir\030\002 \001(\t\022\023\n\013r" +
      "un_as_user\030\003 \001(\t\"t\n\022ServiceRoleRequest\022\024" +
      "\n\014service_name\030\001 \001(\t\022\031\n\021service_role_nam" +
      "e\030\002 \001(\t\022\024\n\014json_payload\030\003 \001(\t\022\027\n\017config_" +
      "map_json\030\004 \001(\t\"&\n\020UnixGroupRequest\022\022\n\ngr" +
      "oup_name\030\001 \001(\t\"M\n\017UnixUserRequest\022\020\n\010use" +
      "rname\030\001 \001(\t\022\022\n\nmain_group\030\002 \001(\t\022\024\n\014other" +
      "_groups\030\003 \001(\t\"B\n\022FileOperateRequest\022\014\n\004p" +
      "ath\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\022\r\n\005lines\030\003 \003(" +
      "\t\"A\n\022AlertConfigRequest\022\022\n\ncluster_id\030\001 " +
      "\001(\005\022\027\n\017config_map_json\030\002 \001(\t2\203\013\n\024WorkerC" +
      "ommandService\022K\n\004Ping\022 .com.datasophon.g" +
      "rpc.PingRequest\032!.com.datasophon.grpc.Ex" +
      "ecResultPb\022W\n\nExecuteCmd\022&.com.datasopho" +
      "n.grpc.ExecuteCmdRequest\032!.com.datasopho" +
      "n.grpc.ExecResultPb\022O\n\006GetLog\022\".com.data" +
      "sophon.grpc.GetLogRequest\032!.com.datasoph" +
      "on.grpc.ExecResultPb\022`\n\022InstallServiceRo" +
      "le\022\'.com.datasophon.grpc.ServiceRoleRequ" +
      "est\032!.com.datasophon.grpc.ExecResultPb\022b" +
      "\n\024ConfigureServiceRole\022\'.com.datasophon." +
      "grpc.ServiceRoleRequest\032!.com.datasophon" +
      ".grpc.ExecResultPb\022^\n\020StartServiceRole\022\'" +
      ".com.datasophon.grpc.ServiceRoleRequest\032" +
      "!.com.datasophon.grpc.ExecResultPb\022]\n\017St" +
      "opServiceRole\022\'.com.datasophon.grpc.Serv" +
      "iceRoleRequest\032!.com.datasophon.grpc.Exe" +
      "cResultPb\022`\n\022RestartServiceRole\022\'.com.da" +
      "tasophon.grpc.ServiceRoleRequest\032!.com.d" +
      "atasophon.grpc.ExecResultPb\022_\n\021ServiceRo" +
      "leStatus\022\'.com.datasophon.grpc.ServiceRo" +
      "leRequest\032!.com.datasophon.grpc.ExecResu" +
      "ltPb\022[\n\017CreateUnixGroup\022%.com.datasophon" +
      ".grpc.UnixGroupRequest\032!.com.datasophon." +
      "grpc.ExecResultPb\022[\n\017DeleteUnixGroup\022%.c" +
      "om.datasophon.grpc.UnixGroupRequest\032!.co" +
      "m.datasophon.grpc.ExecResultPb\022Y\n\016Create" +
      "UnixUser\022$.com.datasophon.grpc.UnixUserR" +
      "equest\032!.com.datasophon.grpc.ExecResultP" +
      "b\022Y\n\016DeleteUnixUser\022$.com.datasophon.grp" +
      "c.UnixUserRequest\032!.com.datasophon.grpc." +
      "ExecResultPb\022Y\n\013OperateFile\022\'.com.dataso" +
      "phon.grpc.FileOperateRequest\032!.com.datas" +
      "ophon.grpc.ExecResultPb\022a\n\023GenerateAlert" +
      "Config\022\'.com.datasophon.grpc.AlertConfig" +
      "Request\032!.com.datasophon.grpc.ExecResult" +
      "PbB(\n\027com.datasophon.grpc.apiB\013WorkerPro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.datasophon.grpc.api.CommonProto.getDescriptor(),
        });
    internal_static_com_datasophon_grpc_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_datasophon_grpc_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_PingRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_datasophon_grpc_ExecuteCmdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor,
        new java.lang.String[] { "Commands", "CommandLine", });
    internal_static_com_datasophon_grpc_GetLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_datasophon_grpc_GetLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_GetLogRequest_descriptor,
        new java.lang.String[] { "LogFile", "BaseDir", "RunAsUser", });
    internal_static_com_datasophon_grpc_ServiceRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_datasophon_grpc_ServiceRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_ServiceRoleRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ServiceRoleName", "JsonPayload", "ConfigMapJson", });
    internal_static_com_datasophon_grpc_UnixGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_datasophon_grpc_UnixGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_UnixGroupRequest_descriptor,
        new java.lang.String[] { "GroupName", });
    internal_static_com_datasophon_grpc_UnixUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_datasophon_grpc_UnixUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_UnixUserRequest_descriptor,
        new java.lang.String[] { "Username", "MainGroup", "OtherGroups", });
    internal_static_com_datasophon_grpc_FileOperateRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_datasophon_grpc_FileOperateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_FileOperateRequest_descriptor,
        new java.lang.String[] { "Path", "Content", "Lines", });
    internal_static_com_datasophon_grpc_AlertConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_datasophon_grpc_AlertConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_AlertConfigRequest_descriptor,
        new java.lang.String[] { "ClusterId", "ConfigMapJson", });
    com.datasophon.grpc.api.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
