// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker.proto

// Protobuf Java Version: 3.25.5
package com.datasophon.grpc.api;

public final class WorkerProto {
  private WorkerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_ExecuteCmdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_GetLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_GetLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_datasophon_grpc_ServiceRoleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_datasophon_grpc_ServiceRoleRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014worker.proto\022\023com.datasophon.grpc\032\014com" +
      "mon.proto\"\036\n\013PingRequest\022\017\n\007message\030\001 \001(" +
      "\t\";\n\021ExecuteCmdRequest\022\020\n\010commands\030\001 \003(\t" +
      "\022\024\n\014command_line\030\002 \001(\t\"H\n\rGetLogRequest\022" +
      "\020\n\010log_file\030\001 \001(\t\022\020\n\010base_dir\030\002 \001(\t\022\023\n\013r" +
      "un_as_user\030\003 \001(\t\"t\n\022ServiceRoleRequest\022\024" +
      "\n\014service_name\030\001 \001(\t\022\031\n\021service_role_nam" +
      "e\030\002 \001(\t\022\024\n\014json_payload\030\003 \001(\t\022\027\n\017config_" +
      "map_json\030\004 \001(\t2\325\006\n\024WorkerCommandService\022" +
      "K\n\004Ping\022 .com.datasophon.grpc.PingReques" +
      "t\032!.com.datasophon.grpc.ExecResultPb\022W\n\n" +
      "ExecuteCmd\022&.com.datasophon.grpc.Execute" +
      "CmdRequest\032!.com.datasophon.grpc.ExecRes" +
      "ultPb\022O\n\006GetLog\022\".com.datasophon.grpc.Ge" +
      "tLogRequest\032!.com.datasophon.grpc.ExecRe" +
      "sultPb\022`\n\022InstallServiceRole\022\'.com.datas" +
      "ophon.grpc.ServiceRoleRequest\032!.com.data" +
      "sophon.grpc.ExecResultPb\022b\n\024ConfigureSer" +
      "viceRole\022\'.com.datasophon.grpc.ServiceRo" +
      "leRequest\032!.com.datasophon.grpc.ExecResu" +
      "ltPb\022^\n\020StartServiceRole\022\'.com.datasopho" +
      "n.grpc.ServiceRoleRequest\032!.com.datasoph" +
      "on.grpc.ExecResultPb\022]\n\017StopServiceRole\022" +
      "\'.com.datasophon.grpc.ServiceRoleRequest" +
      "\032!.com.datasophon.grpc.ExecResultPb\022`\n\022R" +
      "estartServiceRole\022\'.com.datasophon.grpc." +
      "ServiceRoleRequest\032!.com.datasophon.grpc" +
      ".ExecResultPb\022_\n\021ServiceRoleStatus\022\'.com" +
      ".datasophon.grpc.ServiceRoleRequest\032!.co" +
      "m.datasophon.grpc.ExecResultPbB(\n\027com.da" +
      "tasophon.grpc.apiB\013WorkerProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.datasophon.grpc.api.CommonProto.getDescriptor(),
        });
    internal_static_com_datasophon_grpc_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_datasophon_grpc_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_PingRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_datasophon_grpc_ExecuteCmdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_ExecuteCmdRequest_descriptor,
        new java.lang.String[] { "Commands", "CommandLine", });
    internal_static_com_datasophon_grpc_GetLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_datasophon_grpc_GetLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_GetLogRequest_descriptor,
        new java.lang.String[] { "LogFile", "BaseDir", "RunAsUser", });
    internal_static_com_datasophon_grpc_ServiceRoleRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_datasophon_grpc_ServiceRoleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_datasophon_grpc_ServiceRoleRequest_descriptor,
        new java.lang.String[] { "ServiceName", "ServiceRoleName", "JsonPayload", "ConfigMapJson", });
    com.datasophon.grpc.api.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
