app:
  - name: VALKEY
    version: 8.1.8
    deployType: physical
    roles:
      - name: ValkeyMaster
        deployHosts:
          - ddh-02
      - name: ValkeyExporter
        deployHosts:
          - ddh-02
  - name: ELASTICSEARCH
    version: 9.4.3
    deployType: physical
    roles:
      - name: ElasticSearch
        deployHosts:
          - ddh-02
  - name: NACOS
    version: 3.2.2
    deployType: physical
    roles:
      - name: NacosServer
        deployHosts:
          - ddh-02
  - name: DS
    version: 3.4.1
    deployType: physical
    roles:
      - name: ApiServer
        deployHosts:
          - ddh-02
      - name: MasterServer
        deployHosts:
          - ddh-02
      - name: WorkerServer
        deployHosts:
          - ddh-03
          - ddh-04
          - ddh-05
      - name: AlertServer
        deployHosts:
          - ddh-02
  - name: APISIX
    version: 3.17.0
    deployType: physical
    roles:
      - name: Apisix
        deployHosts:
          - ddh-01
