-- Paimon ODS 层建表（Flink SQL 方言）
-- D2：ODS 全部落 Paimon（RustFS S3），全列 STRING（对齐 D10 全 VARCHAR 精神，Paimon 无 VARCHAR 类型故用等价 STRING）
--
-- 执行方式：Flink SQL Client 先注册 catalog `paimon_s3`（type=paimon，warehouse 指向
-- Gravitino `paimon_s3` catalog 同一个 S3 路径——该 catalog 的 catalog-backend 是 filesystem，
-- 本质就是自描述的文件系统目录，Flink 原生 Paimon catalog 直连同一路径即可看到/建出同一批表，
-- 不需要经过 Gravitino 的 Flink 连接器），再 `USE CATALOG paimon_s3; USE lineage_flink_verify;`
-- 跑本文件。CREATE CATALOG 语句含 S3 凭据，不进本文件，见运维侧未入库的 catalog 注册脚本。
CREATE DATABASE IF NOT EXISTS `lineage_flink_verify`;
USE `lineage_flink_verify`;

DROP TABLE IF EXISTS `ods_smxt_lancet_aims_pat_surgery_full_daily`;
-- 病人手术表（ODS，源=MySQL pat_surgery，CDC 驱动主流）
CREATE TABLE `ods_smxt_lancet_aims_pat_surgery_full_daily` (
  `ID` STRING,
  `PATIENT_ID` STRING,
  `PATIENT_SYNC_ID` STRING,
  `RECORD_ID` STRING,
  `RECORD_TYPE` STRING,
  `TYPE` STRING,
  `GOING_STATUS` STRING,
  `INFECTION_COUNT` STRING,
  `ABNORMAL_COUNT` STRING,
  `VERIFY_CONTENT` STRING,
  `NAME` STRING,
  `ID_CARD` STRING,
  `GENDER` STRING,
  `AGE` STRING,
  `HEIGHT` STRING,
  `WEIGHT` STRING,
  `BLOOD_TYPE` STRING,
  `CONTACTS_PHONE` STRING,
  `ADDRESS` STRING,
  `ADMISSION_NUMBER` STRING,
  `ADMISSION_TIMES` STRING,
  `BED_NUMBER` STRING,
  `HOSPITAL_ID` STRING,
  `HOSPITAL_NAME` STRING,
  `DEPT_ID` STRING,
  `DEPT_NAME` STRING,
  `DOCTOR_DEPT_ID` STRING,
  `DOCTOR_DEPT_NAME` STRING,
  `APPLY_DEPT_ID` STRING,
  `APPLY_DEPT_NAME` STRING,
  `DIAGNOSIS_CONTENT` STRING,
  `INFECTION_HISTORY` STRING,
  `SEPICAL_PREPARATION` STRING,
  `ROOM_ID` STRING,
  `ROOM_NAME` STRING,
  `IS_TRANSFER_ROOM` STRING,
  `SERIAL_INTERVAL` STRING,
  `SURGERY_SERIAL` STRING,
  `SURGERY_DATE` STRING,
  `SURGERY_NAME` STRING,
  `SURGERY_LEVEL` STRING,
  `SURGERY_INCISION` STRING,
  `SURGERY_DOCTOR_ID` STRING,
  `SURGERY_DOCTOR_NAME` STRING,
  `SURGERY_DOCTOR` STRING,
  `SURGERY_ASSISTANT` STRING,
  `CIRCUIT_NURSE1_ID` STRING,
  `CIRCUIT_NURSE1_NAME` STRING,
  `CIRCUIT_NURSE2_ID` STRING,
  `CIRCUIT_NURSE2_NAME` STRING,
  `EQUIPMENT_NURSE1_ID` STRING,
  `EQUIPMENT_NURSE1_NAME` STRING,
  `EQUIPMENT_NURSE2_ID` STRING,
  `EQUIPMENT_NURSE2_NAME` STRING,
  `PERFUSION_NURSE_ID` STRING,
  `PERFUSION_NURSE_NAME` STRING,
  `APPLY_TIME` STRING,
  `OR_DEPT_ID` STRING,
  `OR_DEPT_NAME` STRING,
  `EC_DEPT_ID` STRING,
  `EC_DEPT_NAME` STRING,
  `AN_DEPT_ID` STRING,
  `AN_DEPT_NAME` STRING,
  `IS_SECOND` STRING,
  `SECOND_REASON` STRING,
  `ANES_DOCTOR1_ID` STRING,
  `ANES_DOCTOR1_NAME` STRING,
  `ANES_DOCTOR2_ID` STRING,
  `ANES_DOCTOR2_NAME` STRING,
  `ANES_ASSISTANT` STRING,
  `PERFUSION_DOCTOR_ID` STRING,
  `PERFUSION_DOCTOR_NAME` STRING,
  `ANES_TYPE_CODE` STRING,
  `ANES_TYPE_NAME` STRING,
  `ANES_TYPE_PARENT_CODE` STRING,
  `ANES_TYPE_PARENT_NAME` STRING,
  `IS_ANALGESIC` STRING,
  `IS_FIRST` STRING,
  `STATE` STRING,
  `PREVIOUS_LEAVE_TIME` STRING,
  `INDUCE_BEGIN_TIME` STRING,
  `INDUCE_END_TIME` STRING,
  `SURGERY_ENTRY_TIME` STRING,
  `SURGERY_LEAVE_TIME` STRING,
  `SURGERY_BEGIN_TIME` STRING,
  `SURGERY_END_TIME` STRING,
  `ANES_BEGIN_TIME` STRING,
  `ANES_END_TIME` STRING,
  `CREATOR_ID` STRING,
  `CREAT_TIME` STRING,
  `MODIFIER_ID` STRING,
  `MODIFY_TIME` STRING,
  `ASA_CODE` STRING,
  `LEAVE_WARD_TIME` STRING,
  `ARRIVAL_OR_DEPT_TIME` STRING,
  `INTO_OR_DEPT_TIME` STRING,
  `DOCTOR_ARRIVAL_TIME` STRING,
  `PACU_DOCTOR_ID` STRING,
  `PACU_DOCTOR_ID1` STRING,
  `PACU_ENTER_NURSE_ID` STRING,
  `PACU_LEAVE_NURSE_ID` STRING,
  `PACU_BEGIN_TIME` STRING,
  `PACU_END_TIME` STRING,
  `PACU_REVIVAL_TIME` STRING,
  `DISCHARGE_DATE` STRING,
  `OR_EXTEND_INFO` STRING,
  `ANES_EXTEND_INFO` STRING,
  `QC_EXTEND_INFO` STRING,
  `LEAVE_ALDRETE` STRING,
  `SEAL_MEDICAL` STRING,
  `VALID` STRING,
  PRIMARY KEY (`ID`) NOT ENFORCED
) WITH (
  'bucket' = '4'
);

DROP TABLE IF EXISTS `ods_smxt_lancet_aims_pat_surgery_notice_full_daily`;
-- 病人手术通知表（ODS，源=MySQL pat_surgery_notice，Lookup 维表）
CREATE TABLE `ods_smxt_lancet_aims_pat_surgery_notice_full_daily` (
  `ID` STRING,
  `TYPE` STRING,
  `SYNC_ID` STRING,
  `PATIENT_ID` STRING,
  `APPLY_DEPT_ID` STRING,
  `APPLY_USER_ID` STRING,
  `APPLY_TIME` STRING,
  `APPLY_START_TIME` STRING,
  `SURGERY_DOCTOR_ID` STRING,
  `DOCTOR_DEPT_ID` STRING,
  `SURGERY_DATE` STRING,
  `BODYPOSITION_CODE` STRING,
  `OR_DEPT_ID` STRING,
  `EC_DEPT_ID` STRING,
  `AN_DEPT_ID` STRING,
  `ISOLATION_CODE` STRING,
  `IS_SECOND` STRING,
  `SECOND_REASON` STRING,
  `SECOND_LINK_ID` STRING,
  `ANES_TYPE_CODE` STRING,
  `ANES_TYPE_NAME_APPLY` STRING,
  `ROOM_SERIAL` STRING,
  `SURGERY_SERIAL` STRING,
  `SEPICAL_PREPARATION` STRING,
  `INSTRUMENT_REQUIREMENT` STRING,
  `REMARK` STRING,
  `IS_REGISTER` STRING,
  `IS_RESERVE` STRING,
  `IS_URGENT` STRING,
  `IS_FROZEN` STRING,
  `EXTEND_INFO` STRING,
  `VALID` STRING,
  PRIMARY KEY (`ID`) NOT ENFORCED
) WITH (
  'bucket' = '4'
);

DROP TABLE IF EXISTS `ods_smxt_lancet_aims_sys_dept_full_daily`;
-- 科室表（ODS，源=MySQL sys_dept，Lookup 维表）
CREATE TABLE `ods_smxt_lancet_aims_sys_dept_full_daily` (
  `ID` STRING,
  `SYNC_ID` STRING,
  `HOSPITAL_ID` STRING,
  `PARENT_ID` STRING,
  `PATH_ID` STRING,
  `TYPE` STRING,
  `NAME` STRING,
  `ALIAS` STRING,
  `DESCRIPTION` STRING,
  `EXTEND_ATTRIBUTE` STRING,
  `SORT_NUMBER` STRING,
  `VALID` STRING,
  PRIMARY KEY (`ID`) NOT ENFORCED
) WITH (
  'bucket' = '4'
);

DROP TABLE IF EXISTS `ods_smxt_lancet_aims_sys_user_full_daily`;
-- 医生人员表（ODS，源=MySQL sys_user，Lookup 维表）
CREATE TABLE `ods_smxt_lancet_aims_sys_user_full_daily` (
  `ID` STRING,
  `DEPT_ID` STRING,
  `HOSPITAL_ID` STRING,
  `SYNC_ID` STRING,
  `CA_SYNC_ID` STRING,
  `NAME` STRING,
  `ALIAS` STRING,
  `GENDER` STRING,
  `BIRTHDAY` STRING,
  `TYPE` STRING,
  `PHOTO` STRING,
  `SIGNATURE` STRING,
  `FINGERPRINT` STRING,
  `EMAIL` STRING,
  `PHONE_NUMBER` STRING,
  `WECHAT_NUMBER` STRING,
  `JOB_NUMBER` STRING,
  `ID_CARD` STRING,
  `JOB_TITLE_CODE` STRING,
  `JOB_TITLE` STRING,
  `JOB_TITLE_YEAR` STRING,
  `JOINING_TIME` STRING,
  `DOCTOR_CERT_CODE` STRING,
  `ENERGY_LEVEL` STRING,
  `DESCRIPTION` STRING,
  `MEDICAL_TYPE` STRING,
  `EDUCATION_CODE` STRING,
  `GRADUATE_INSTITUTIONS` STRING,
  `MAJOR` STRING,
  `EXTEND_ATTRIBUTE` STRING,
  `VALID` STRING,
  `TAG` STRING,
  `MODIFIER_ID` STRING,
  `MODIFY_TIME` STRING,
  PRIMARY KEY (`ID`) NOT ENFORCED
) WITH (
  'bucket' = '4'
);

DROP TABLE IF EXISTS `ods_xy_jxkh_v_ryb_full_daily`;
-- 绩效表（ODS，D7：无 MySQL 源，血缘图根节点，一次性灌注）
CREATE TABLE `ods_xy_jxkh_v_ryb_full_daily` (
  `ygbh` STRING,
  `xm` STRING,
  `xzksbh` STRING,
  `xzksmc` STRING,
  PRIMARY KEY (`ygbh`) NOT ENFORCED
) WITH (
  'bucket' = '4'
);

DROP TABLE IF EXISTS `ods_xy_jxkh_xzksjxdyb_full_daily`;
-- 绩效表（ODS，D7：无 MySQL 源，血缘图根节点，一次性灌注）
CREATE TABLE `ods_xy_jxkh_xzksjxdyb_full_daily` (
  `xzksbh` STRING,
  `xzksmc` STRING,
  `jxksmc` STRING,
  PRIMARY KEY (`xzksbh`) NOT ENFORCED
) WITH (
  'bucket' = '4'
);

DROP TABLE IF EXISTS `ods_xy_jxkh_txryjxksb_full_daily`;
-- 绩效表（ODS，D7：无 MySQL 源，血缘图根节点，一次性灌注）
CREATE TABLE `ods_xy_jxkh_txryjxksb_full_daily` (
  `ygbh` STRING,
  `xm` STRING,
  `jxksmc` STRING,
  `ks` STRING,
  `xmpy` STRING,
  `xzksmc` STRING,
  `zwjb` STRING,
  `przw` STRING,
  `gwxl` STRING,
  `zt` STRING,
  PRIMARY KEY (`ygbh`) NOT ENFORCED
) WITH (
  'bucket' = '4'
);

DROP TABLE IF EXISTS `ods_xy_jxkh_cwc_hsjxdyb_full_daily`;
-- 绩效表（ODS，D7：无 MySQL 源，血缘图根节点，一次性灌注）
CREATE TABLE `ods_xy_jxkh_cwc_hsjxdyb_full_daily` (
  `ksbm` STRING,
  `ksmc` STRING,
  `ykjxdy` STRING,
  `jxdy` STRING,
  `jxks` STRING,
  PRIMARY KEY (`ksbm`) NOT ENFORCED
) WITH (
  'bucket' = '4'
);
