apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datasophon-k8s-agent.fullname" . }}-config
  labels:
    {{- include "datasophon-k8s-agent.labels" . | nindent 4 }}
data:
  application.yaml: |
    {{- .Values.config.applicationYaml | nindent 4 }}
  common.properties: |
    {{- .Values.config.commonProperties | nindent 4 }}
